### ISSUE TITLE
Unable to print `INFO` and `ERROR` logs to different streams

### ISSUE THREAD

**Issue by MadhukaHarith92** [uber-go/zap#1014]
I tried out the basic configurations example in Uber Zap [[1]](https://pkg.go.dev/go.uber.org/zap#example-package-BasicConfiguration). The following is the code.
```
package main

import (
	"encoding/json"
	"fmt"
	"go.uber.org/zap"
	"os"
)

func main() {
	rawJSON := []byte(`{
	  "level": "debug",
	  "encoding": "json",
	  "outputPaths": ["stdout"],
	  "errorOutputPaths": ["stderr"],
	  "encoderConfig": {
	    "messageKey": "message",
	    "levelKey": "level",
	    "levelEncoder": "lowercase"
	  }
	}`)

	var cfg zap.Config
	if err := json.Unmarshal(rawJSON, &cfg); err != nil {
		panic(err)
	}
	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}
	defer logger.Sync()

	logger.Info("info log")
	logger.Error("error log")

	fmt.Fprintln(os.Stdout, "out")
	fmt.Fprintln(os.Stderr, "err")
}
```

However when I execute `./uberzap 2>/dev/null` I get the following output.
```
{"level":"info","message":"info log"}
{"level":"error","message":"error log"}
out
```

But my expected output is
```
{"level":"info","message":"info log"}
out
```

since I have given the configuration to print error output to `stderr` stream (`"errorOutputPaths": ["stderr"]`).

Is this the expected behavior or have I missed any configuration.

[1] https://pkg.go.dev/go.uber.org/zap#example-package-BasicConfiguration

**Comment by abhinav** [comment]
Hello! Sorry, there has been a misunderstanding.

`errorOutputPaths` does not specify where the output of error level log entries go.
It specifies where the internal errors from Zap go.

```
	// ErrorOutputPaths is a list of URLs to write internal logger errors to.
	// The default is standard error.
	//
	// Note that this setting only affects internal errors; for sample code that
	// sends error-level logs to a different location from info- and debug-level
	// logs, see the package-level AdvancedConfiguration example.
	ErrorOutputPaths []string `json:"errorOutputPaths" yaml:"errorOutputPaths"`
```

To achieve what you desire, you'll have to write a custom implementation of [zapcore.Core](https://pkg.go.dev/go.uber.org/zap@v1.19.1/zapcore#Core)
that redirects [Core.Write](https://pkg.go.dev/go.uber.org/zap@v1.19.1/zapcore#Core.Write) calls based on [Entry.Level](https://pkg.go.dev/go.uber.org/zap@v1.19.1/zapcore#Entry.Level).

The implementation will likely look similar to the [Tee Core](https://pkg.go.dev/go.uber.org/zap@v1.19.1/zapcore#NewTee) with one difference:
in Write, instead of delegating to all wrapped cores, you would delegate based to one based on level.


Closing because answered.
