### ISSUE TITLE
please compare zap with klog

### ISSUE THREAD

**Issue by saksham189** [uber-go/zap#1023]
Is it possible to get some comparison to kubernetes logging library klog. How is this package "better" in whatever sense it may be. (e.g. performance, structured, etc.) I know recently that klog has also started supporting structured logging. So would it be possible to compare the two in terms of features, performance and other benchmarks ?

**Comment by abhinav** [comment]
klog does not appear to be a library meant to replace Zap or the other libraries that Zap is compared against in our [documentation and benchmarks](https://github.com/uber-go/zap#performance).

For one, [klog](https://pkg.go.dev/k8s.io/klog/v2) appears to operate on a single global logger. That is not the case with Zap or the other logging libraries in our comparisons.
Secondly, high performance has been a goal of Zap from day one. That does not appear to be the case with klog, which is okay because that's not the use case they're trying to fit into.

We'll welcome a PR adding klog to the benchmarks, but we don't feel that it's necessary.
