### ISSUE TITLE
Is it possible to check whether a field is already defined and either drop it or overwrite it?

### ISSUE THREAD

**Issue by polds** [uber-go/zap#1025]
I'm wondering if it's possible check whether a field is already defined. I find some log entries get to the point where the same context is defined multiple times throughout the stack so you end up with `{"i": "foo", "i": "foo", "i": "foo"}`, etc.

Is it possible (maybe with a Hook?) to check if the field is already present and decide whether to not log, or overwrite the field?

If a Hook is the answer I'm not sure what that would look like.

**Comment by abhinav** [comment]
Hey, sorry it's not possible to detect this in Zap today.

This came up in #622 before and that issue has some ideas on
what Zap could do internally to detect and prevent this.
However, we've generally not prioritized that feature because
we don't frequently see intentionally duplicate keys in production often.
And for the unintentional duplicates, we'd rather have the issue found and fixed rather than ignored.

Closing in favor of #622
