### ISSUE TITLE
Speed discrepancy between zap.NewProduction() and building a logger from zap.NewProductionEncoderConfig()

### ISSUE THREAD

**Issue by dmayfieldyahoo** [uber-go/zap#1066]
I have written a custom encoder based on the JSON encoder to work with our logging standards.  When deploying a new build with Zap and the custom encoder, we see significant performance loss over the previous logger.  Digging into this, I ran some benchmarks on my laptop, and found a surprising result.

The zap logger built from zap.NewProduction() finishes the benchmark with the following results:
` 5089264	       229.1 ns/op	     131 B/op	       1 allocs/op`
The zap logger built from zap.NewProductionEncoderConfig(), zapcore.NewJSONEncoder(), and zapcore.Lock(zapcore.AddSync(os.stderr) finishes the benchmark with the following results:
`  569798	      2203 ns/op	     128 B/op	       1 allocs/op`
The custom encoder is the same order of magnitude as the JSON encoder:
 `658821	      1860 ns/op	     128 B/op	       1 allocs/op`

The flame graphs show that both setups are doing approximately the same thing.  What am I doing wrong that the manual construction is an order of magnitude slower?

```
func BenchmarkZapDefault(b *testing.B) {
	l, err := zap.NewProduction()
	if err != nil {
		b.Fatal(err)
	}
	for i := 0; i < b.N; i++ {
		l.Info("Log this silly thing", zap.Bool("isTru", true), zap.String("isString", "yup, a string!"))
	}
}

func BenchmarkZapJSONEncoder(b *testing.B) {
	pc := zap.NewProductionEncoderConfig()
	enc := zapcore.NewJSONEncoder(pc)
	ws := zapcore.AddSync(os.Stderr)
	zc := zapcore.NewCore(enc, ws, zap.InfoLevel)
	l := zap.New(zc)
	for i := 0; i < b.N; i++ {
		l.Info("Log this silly thing", zap.Bool("isTru", true), zap.String("isString", "yup, a string!"))
	}
}
```

**Comment by abhinav** [comment]
Hey there! The difference is that NewProduction does more than that.
It [wraps the Core](https://github.com/uber-go/zap/blob/6f34060764b5ea1367eecda380ba8a9a0de3f0e6/config.go#L217-L231) with a [sampler](https://pkg.go.dev/go.uber.org/zap/zapcore#NewSamplerWithOptions) configured here: https://github.com/uber-go/zap/blob/6f34060764b5ea1367eecda380ba8a9a0de3f0e6/config.go#L124-L127

Based on that configuration, if the sampler see more than 100 log entries with the same message and level in the same one second interval, it'll begin dropping logs, keeping every 100th entry.

That's how NewProduction is able to perform better than a vanilla logger built with NewProductionEncoderConfig.

Closing because answered. Feel free to re-open or create a new ticket if you have more questions.
