### ISSUE TITLE
Question on creating custom object encoder for object with primitive array member

### ISSUE THREAD

**Issue by madshov** [uber-go/zap#1073]
Hi, I'm using `ObjectMarshaler` to create log context for a given struct, so that I be able to use `zap.Object`:
```
logger = logger.With(
        zap.Object("order", order),
)
logger. Info("abc")
```

My `Order` struct contains a `[]string` slice of keywords:
```
type Order struct {
	ID       string
	Price    int64
        Keywords []string
       ...
}
```

My question is how do I include this field in the object encoder for `Order`?
```
func (o Order) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddString("id", o.ID)
	enc.AddInt64("price", o.Price)
	enc.AddString("keywords", o.Keywords) // ???
       ...
}

**Comment by abhinav** [comment]
Hey there! Sorry for the delay.

If you have a `[]string` inside a ObjectMarshaler implementation,
you can re-use the [`zap.Strings`](https://pkg.go.dev/go.uber.org/zap#Strings) field constructor
and add it to the encoder with [`Field.AddTo`](https://pkg.go.dev/go.uber.org/zap@v1.21.0/zapcore#Field.AddTo).

```go
func (o Order) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddString("id", o.ID)
	enc.AddInt64("price", o.Price)
	zap.Strings("keywords", o.Keywords).AddTo(enc)
       // ...
}
```

Hope this helps!

Closing because answered.
Feel free to re-open or create a new issue.
