### ISSUE TITLE
the log output is not ordered by time

### ISSUE THREAD

**Issue by crazycs520** [uber-go/zap#1094]
## Problem

```go
func main() {
	logger, _ := zap.NewProduction()
	defer logger.Sync() // flushes buffer, if any
	for i := 0; i <= 10; i++ {
		go func() {
			for j := 0; j < 10; j++ {
				logger.Info("test")
			}
		}()
	}
	time.Sleep(time.Second)
}
```

the output is:

```log
{"level":"info","ts":1651823525.940267,"caller":"log/main.go:14","msg":"test"}
{"level":"info","ts":1651823525.940234,"caller":"log/main.go:14","msg":"test"}
{"level":"info","ts":1651823525.9402711,"caller":"log/main.go:14","msg":"test"}
```

And the log output is not ordered by time, the `ts` of second log is smaller than the first log.

Is there any way to make the log output strictly ordered by time?

**Comment by abhinav** [comment]
Hello, and thanks for the report. We do not consider this a bug. There is no expectation for logs to be ordered by time in Zap. The time at which the log is captured, and the time at which it is written to the output stream can vary--especially with concurrent logging attempts.

Closing because answered. Please feel free to re-open or create new issues if you have any other questions.
