### ISSUE TITLE
Unexpected logging pattern of large uint64 values

### ISSUE THREAD

**Issue by zackls** [uber-go/zap#1213]
**Describe the bug**
I added a field and uint64 value to a call to `log`, and occasionally see negative values logged.

**To Reproduce**
Invoke any log method with any 'large' uint64 value. I believe this issue will occur for values >Int64Max

**Expected behavior**
I would expect a positive value to be logged.

**Additional context**
I believe there is an issue with the handling of the uint64 value type:
```
// Uint64 constructs a field with the given key and value.
func Uint64(key string, val uint64) zapcore.Field {
	return zapcore.Field{Key: key, Type: zapcore.Uint64Type, Integer: int64(val)}
}
```
An int64 cast here will not work as intended for values larger than the max int64. Here is a go playground link illustrating this casting issue: https://go.dev/play/p/8SfRZIOEZm7

I am not deeply familiar with this library, but would propose the logic be refactored to avoid this cast.

**Comment by sywhang** [comment]
It's only stored as an int64 representation since that's what the  `zapcore.Field` expects. But eventually during serialization we look at the field type being `zapcore.Uint64Type` and marshal it back to uint64 type: https://github.com/uber-go/zap/blob/master/zapcore/field.go#L160.

For example: https://go.dev/play/p/krnwVg5BrXV shows Zap logger correctly logging the large uint64 field you have. 

Can you share an example where you're attempting log an Uint64 type to a Zap logger and it's showing up as a negative value?

**Comment by zackls** [comment]
I tried again with a minimal example of the library code and it seems to be handled properly, so likely some other issue. Thanks for your quick response 😃
