### ISSUE TITLE
Request new zapcore.Field -- zap.JSONString

### ISSUE THREAD

**Issue by jjkoh95** [uber-go/zap#1242]
**Is your feature request related to a problem? Please describe.**
Can we have a JSONString field type? It is difficult to capture unknown error response with its type so instead I capture raw byte slice from body. I wish to log the error response as JSON and index the fields, which can then easily be converted into metrics for further analysis.

**Describe the solution you'd like**
I have a custom function to cast JSON string, and wonder if it'll be useful to include it in the core library.
```go
func zapJSONString(k, v string) zapcore.Field {
	var m interface{}
	json.Unmarshal([]byte(v), &m)
	return zap.Any(k, m)
}
```

**Describe alternatives you've considered**
I'm using the custom function above.

**Is this a breaking change?**
No

**Additional context**
If it already exists, please share the relevant APIs.

**Comment by prashantv** [comment]
Since the `Unmarshal` can fail, we'd need to have some sort of error handling (e.g., skip the field, or log the field with an error string, or log a separate <field>Error with the error string).

Given the different possible behaviours, and since it can be implemented simply outside of zap, I'm not sure it's worthwhile to add.

The only possible advantage is if we allowed JSONString fields to be added to the logger as-is (no deserialization + serialization) but that would require additional code to validate that the string is valid JSON, which is additional complexity.

**Comment by jjkoh95** [comment]
Thanks for your response, that's valid and fair

The solution I have is less elegant so was wondering if the core library has something neater to deal with such scenario. Was also wondering if it is also a common problem faced by others.

I'll close this. Thank you
