### ISSUE TITLE
jsonEncoder.truncate leaves potential large-capacity buffers

### ISSUE THREAD

**Issue by mysza** [uber-go/zap#134]
The ```New()``` method of the json encoders pool creates a new ```jsonEncoder``` with a reasonably sized buffer (jsonEncoder.go (51)).

The ```truncate()``` method of ```jsonEncoder``` resets the buffer length to 0, but does not modify its capacity, i.e. the memory buffer acquired to accommodate large chunks of logs and pointed to by the ```enc.bytes``` slice stays as-is after the ```truncate()``` call. As the log data is appended to the ```enc.bytes``` slice, the capacity (and memory usage) will inevitably grow to the size that can fit the largest log message seen so far, which can be quite large if stack trace or custom marshallers are included.

I know that even very very large logs would increase memory usage very little, but still it happens, and my issue is actually a question if this is by design, or you'd rather avoid uncontrolled buffer allocations?

One way of fixing it would be to set a threshold for the buffer capacity, and check buffer capacity against the threshold in ```truncate()``` call (or maybe better in ```Free()``` call). If cap is beyond the threshold, a new buffer could be allocated with predefined fixed size, and the old one left for GC.

The new buffer size could also be determined runtime to be big enough for e.g. 90% of the messages (based on the log history).

**Comment by prashantv** [comment]
@mysza The truncate call intentionally leaves the capacity as is, since we want to reuse existing buffers to avoid allocations.

While we can add checks to `Free` to throw away encoders with large capacity buffers, I don't think it's necessary because of the way `sync.Pool` works. It will clear out objects periodically (currently on every GC afaik), so that memory will be released.

This is very similar to how the standard library's `fmt` package works -- it uses a `sync.Pool` to manage a pool of buffers (backed by `[]byte`).

**Comment by mysza** [comment]
OK great, so it's intentional - was just curious :) Thanks for clarification!
