### ISSUE TITLE
Re-consider sampler bucket keying

### ISSUE THREAD

**Issue by jcorbin** [uber-go/zap#176]
As bumped up against in #172, when we golf the unused `Level` arg out of `sampler.sampled`, sampling currently buckets only by the message string.  We can easily shift to a `struct{Level, string}` key with little effort.

**Comment by jcorbin** [comment]
Another advanced form would be to sample on the `pc uintptr` of some nth-caller, but that will compose poorly for any specific value of N, meaning we'd need to walk `pc`s until we  find one not in zap (even then, it could be wrong for 3rd-party higher-level-loggers)...

**Comment by akshayjshah** [comment]
As we do this, let's make sure to bound the size of the sampler's counter collection - since we're introducing formatted string logging, the cardinality of the message set may be quite large. One option to consider: hash the message using something cheap (perhaps a custom FNV implementation that takes a string) and keep a fixed-size array of counters (or an array per level).

If we later need a mathematically perfect sampler (e.g., for some analytics-type workload), we can add a separate implementation.

**Comment by akshayjshah** [comment]
Landed on dev as part of #252.
