### ISSUE TITLE
Expose a way to create a new Logger with Meta

### ISSUE THREAD

**Issue by jsternberg** [uber-go/zap#193]
At the moment, the only way to create a `zap.Logger` is to use `zap.New` and pass in the encoder and options. If you want to create the `zap.Meta` separately to share it between loggers, there's no way I can find to currently do it even though the other methods like `Clone()` and `MakeMeta()` are public.

**Comment by akshayjshah** [comment]
This is certainly true, and it is indeed irritating. We're doing a bunch of pre-1.0 refactoring on the dev branch that'll remove this problem (and greatly reduce the number of methods that extension authors need to implement). Along the way, though, the whole notion of a `Meta` changes.

I'm going to close this issue, since it's not quite relevant to the direction we're going in, but I'm very interested in feedback on the extension-writing process. Would love your thoughts post-1.0.
