### ISSUE TITLE
Log and post to HTTP endpoint

### ISSUE THREAD

**Issue by thalesfsp** [uber-go/zap#196]
Hi @akshayjshah, @heyimalex

 I would like to know if it's possible to, everytime `log.{ANY_LEVEL}.({ANY_MESSAGE})` is called an HTTP post to `http://a.b/c` is made with the level and message. Is it possible to achieve with Hooks? Context: ELK stack.

Thanks!

**Comment by heyimalex** [comment]
Yeah, you can do this with a Hook,

**Comment by akshayjshah** [comment]
Actually, this isn't possible with hooks - they're useful mostly to add extra bits of context to the final logger output.

In general, the best way to do this is to write your own `WriteSyncer` implementation that pushes data over HTTP instead of writing to a local file. You'd then pass an instance of your `WriteSyncer` to the logger's `Output` option.

In the context of the ELK stack, though, check out [Filebeat](https://www.elastic.co/products/beats/filebeat) - it's a small daemon process that tails your application's log files and pushes them to Logstash (or Kafka). That lets your application stay fast and lean, and offloads log shipping to a dedicated process. This is the approach we're moving to internally, and it works quite well.
