### ISSUE TITLE
please compare zap with glog

### ISSUE THREAD

**Issue by einthusan** [uber-go/zap#219]
Is it possible to get some comparison to google's glog. How is this package "better" in whatever sense it may be. (e.g. performance, structured, etc.) We currently use glog and want to know what is the convincing argument for many people who are using glog to switch to zap. Not trying to troll, a seriously genuine question.

**Comment by akshayjshah** [comment]
`glog` isn't a structured logging library, so there's not much to compare. If you'd prefer to `fmt.Printf`-style logging, you should stick to `glog` or the standard library. Performance-wise, `glog` is about the same as [zap's `Standardize` wrapper](https://godoc.org/go.uber.org/zap/zwrap#Standardize).

Rather than re-hashing the benefits of structured logging, I'll just refer you to https://www.thoughtworks.com/radar/techniques/structured-logging and https://www.elastic.co/blog/structured-logging-filebeat.
