### ISSUE TITLE
Question about v1.0

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#305]
Hey dude , I have read the new code on master branch. It's interface seems has changed alot from last version. Lots of new features added but the project also become complicated. 

I wonder if this is almost the final interface we will get in v1.0 ? Is there any big changes WIP before release? Cause I found milestone v1.0 has only 1 issue work in progress.

**Comment by akshayjshah** [comment]
Yep, this should be very close to the final interface.

I'm not *planning* any more changes - that's why this is a release candidate. If we turn up a critical bug or a major usability problem, though, I'm reserving the right to make breaking changes for a few weeks.

If you want to be absolutely safe, pin your project to version `0.1.0-beta.1` until the final 1.0 release.
