### ISSUE TITLE
Add a Field that prints the address of arbitrary interfaces

### ISSUE THREAD

**Issue by skipor** [uber-go/zap#322]
I found that often needed to log just pointer to some interface object, as small unique id. 
It seems nice to have such ability in zap pkg.

Now I have temporary hack with large overhead:
```go
func Pointer(key string, ptr interface{}) zapcore.Field {
	return zap.Stringer("higher", ptrField{ptr})
}
type ptrField struct{ ptr interface{} }
func (f ptrField) String() string {
	return fmt.Sprintf("%p", f.ptr)
}
```

Also, there is problem, when passed object is not pointer. I propose to log it as `Any` in such case, and add `<key>Error` field, as `AddObject` do on error.

**Comment by akshayjshah** [comment]
The only ways that I know of to get the address of an arbitrary pointer are `unsafe.Pointer` and `reflect.Value.Pointer`. I'm categorically opposed to taking a direct dependency on the `unsafe` package in zap - it's just too unusual. I'm also opposed - though less so - to using reflection for this, since it's easy to trigger a panic.

The good news is that adding this API is backwards-compatible, so we don't need to decide right away.

In the short term, I suggest using either `reflect` or `unsafe` in your `Pointer` function - both will be faster than what you're currently using. I suspect that `unsafe` will be much faster than `reflect`, but it's unsafe :)

I'll leave this issue open - if it accumulates enough emoji-votes, we can consider adding it in a point release.

**Comment by akshayjshah** [comment]
Closing this issue out; I don't see a way to accomplish this that's both fast and safe. Unless we can be both performant and panic-free, I don't want to pull this feature into zap itself.

I'm definitely in favor of third-party package exposing their own `zap.Field` constructors - anything you come up with for your own needs can use `zap.Uintptr` or `zap.String` under the hood. I certainly won't be upset if you want to maintain a `zapextras` package :)
