### ISSUE TITLE
Logging to a file seems broken

### ISSUE THREAD

**Issue by MatonAnthony** [uber-go/zap#357]
Hello,

When I try to log to a file, it keep posting to stderr/stdout instead of writing to the file.

```go
func initializer() {
	filename := fmt.Sprintf("watchdog-%s.log", time.Now().Format("2006-01-02 15:04:05"))
	logger_file, err := os.Create(filename)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Creation of log file errored!")
		os.Exit(-1)
	}
	logger, err = zap.NewProduction(zap.ErrorOutput(logger_file))

	logger.Info("Successful initialization")
}
```

I might be doing something incredibly stupid but I don't think so.
The file is created without any hassle with a correct set of permissions.
`-rw-r--r--  1 anthony  staff     0  8 mar 10:43 watchdog-2017-03-08 10:43:08.log`

I tried to look at the code to find why it is not working but I didn't find anything.

**Comment by noxiouz** [comment]
ErrorOutput options sets an output for errors of logging systems, not what you log.
AFAIK, there is no option for your case, so you can do it like this:
```go
cfg := NewProductionConfig()
cfg.OutputPaths = []string{"yourfilepath"}
logger, err = cfg.Build()
```
Or build `zapcore.New` and set options you need

**Comment by MatonAnthony** [comment]
Oh ok, I thought Output had been renamed ErrorsOutput.
Since I saw an example in #100.

Thank you for the help, sorry for the "non-existing bug".

And then a last question, would it be a hard patch to make or a good first contribution ?

**Comment by noxiouz** [comment]
I'm not a maintainer, but in my opinion it looks reasonable to have that option. I would be glad to see that contribution

**Comment by akshayjshah** [comment]
Hey @MatonAnthony - glad you asked! As @noxiouz points out, `ErrorOutput` tells the logger where to write internal error messages. To customize common options like the output file(s), define a `zap.Config` struct and call `Build` on it. (`NewProduction` and `NewDevelopment` are just shortcuts for `NewProductionConfig().Build` and `NewDevelopmentConfig().Build`.) If you want something more exotic, you'll need to construct a `zapcore.Core` yourself and wrap it in a logger with `zap.New`.

This can't be expressed as an logger-level option, because not all loggers write to files - some write to HTTP endpoints, some write only to an in-memory ring buffer, and some write each log level to a different file. If you come up with an elegant way to get around this, I'm happy to look at a PR.
