### ISSUE TITLE
Question: Why there no longer use pool in entry & io.core?  Why CheckedEntry could be dirty?

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#380]
Hi dude, I got 2 question here.

* Why there no longer use pool in entry & io.core?  
  Seems in zap elder version, entry & encoder were both got from a pool. But now I see here is no longer use pool. Is that pool ___can not___ provide a better performance? Is stack memory does not need pool GC can handle this?

* Why CheckedEntry could be dirty? Why we can not avoid this?

**Comment by akshayjshah** [comment]
There are still a number of internal pools - search the zap codebase for `sync.Pool` and you'll find them.

The `Entry` struct in particular doesn't need to be pooled, since it's passed by value (so it stays on the stack). `CheckedEntry` *is* pooled, since it's passed by reference, which is also why it can be dirty - if the user keeps a reference to a `CheckedEntry` and tries to re-use it, they'll end up introducing race conditions and polluting the pool. There's no way to prevent this without introducing more allocations.
