### ISSUE TITLE
Do we want to run benchmarks every time on Travis CI?

### ISSUE THREAD

**Issue by peter-edge** [uber-go/zap#403]
The benchmarks take approximately 2.5 mins, this means the Travis CI build takes ~4.5 mins instead of ~2 mins.

**Comment by akshayjshah** [comment]
I'd like to keep doing this, since it's currently the best defense against performance regressions. The alternative is that a maintainer pulls down every PR and runs `benchcmp` on all supported Go versions. In the few months since I added `make bench` to CI, it's saved us from introducing several unwanted allocations.

I'm indifferent to CI time - doesn't matter to me whether a run takes 30s or 15m, since this isn't a project with hundreds of issues and dozens of interconnected open PRs.
