### ISSUE TITLE
Question on usage of zap.Array() and zap.Object()

### ISSUE THREAD

**Issue by vendion** [uber-go/zap#405]
I upgraded the version of `zap` that my application used from an older, pre-1.x version, of `zap` to a newer version and as I expected there was some breakage but trying to update has left me confused.

First the `zap.Object` seems to have been changed from taking pretty much anything to needing to satisfy a `zapcore.ObjectMarshaler` interface.  There alse seems to be a  `zap.Any()` function that acts like the old `zap.Object` function.  Was this done so there would be more control over what gets logged on a per `struct` bases?  Also what needs done to a struct for it to implement the interface, the [function signature in the docs](https://godoc.org/go.uber.org/zap/zapcore#ObjectMarshaler) just shows that it only returns an `error` so should this method actually handle the printing of the struct?

Secondly the `zap.Array` function seems a but confusing as it also requires that a `zapcore.ArrayMarshaler` interface is satisfied how does this work with native slices?  In my application I have a fair amount of `[]int, []string, [][]int, [][]string` types that I would like logged, and preferably without overloading the native types.  In cases like that would using `zap.Any` be the best way to go?

**Comment by prashantv** [comment]
Hi Adam,

Regarding `zap.Object` and `zap.Any`, this is just a renaming:
 * `zap.Marshaler` was renamed to `zap.Object`. This method does not use any reflection and requires the argument to implement the `ObjectMarshaler` interface. This allows for more control and leads to better performance as reflection can be avoided. For a type to implement `ObjectMarshaler`, it needs to implement a `MarshalLogObject` method which adds fields to the passed in encoder. Here's an example:
https://github.com/uber-go/zap/blob/master/field_test.go#L34

 * `zap.Object` was renamed to `zap.Any` This method uses reflection and since it can also be used for types other than objects (e.g., arrays or primitive values), it has been renamed to `Any`.

For slices of inbuilt primitives like `[]int` and `[]string`, we provide inbuilt functions:
 * `zap.Ints` for `[]int`: https://godoc.org/go.uber.org/zap#Ints
 * `zap.Strings` for `[]string`: https://godoc.org/go.uber.org/zap#Strings

For other types, you can create a custom type that implements `ArrayMarshaler`, or you can use `zap.Any`. `zap.Any` is much easier, but comes at a performance cost.

**Comment by vendion** [comment]
Thanks for the clarification and links that helps a lot.  On the `MarshalLogObject` and`MarshalLogArray` methods it would be helpful if there was an example somewhere in the documentation, if there is I must have over looked it.  The way I was thinking it might have worked would be more like the [Stringer interface](https://golang.org/pkg/fmt/#Stringer) in the `fmt` package of the standard Library but the sole return value of type `error` threw me off.

As for the `zap.Ints` and `zap.Strings` etc they look like thoy only handle one dimensional slices, so in the cases where I have a multi-dimensional slice `zap.Any` or creating my own type and implementing the `zapcore.ArrayMarshaler` interface may be the best case it seems.
