### ISSUE TITLE
Hooks and structured properties

### ISSUE THREAD

**Issue by sshumakov** [uber-go/zap#418]
I am playing with zap logger and hooks functionality that it provides.

I am able to plugin hook and get log level and message. I don't see structured properties however. Message itself doesn't contain properties, nor I can see any collection that I can access to get those properties.

In this file https://github.com/uber-go/zap/blob/e5e74ed8f732eb2d5fb396e463d128a0992e7466/zapcore/hook.go, I see that fields are not passed to the registered hooks.

Is possible to get those properties somehow in message and also structured properties (i.e. key-value pairs)?

**Comment by 23doors** [comment]
I encountered the same issue. Seems really strange for hook to not have access to structured fields.
I worked around this by creating own zapcore.Core and then use zap.WrapCore with NewTee.

You can see example of this approach here:
custom Core with access to fields: https://github.com/uber-go/fx/blob/master/ulog/sentry/sentry.go
initialization: https://github.com/uber-go/fx/blob/master/ulog/log.go#L81

**Comment by akshayjshah** [comment]
Hooks can't access structured fields as a `map[string]interface{}` because the fields are already serialized, and the hooks don't know what encoding is in use. Some encodings, like the console encoder and various ad-hoc text formats, don't even have well-defined unmarshalers.

@23doors has already hit on the right solution: if you need access to the structured data, write a small `zapcore.Core`. You should be able to embed `zapcore.Core` and only implement a little bit of logic. You can then use the `zap.WrapCore` option when constructing your logger - `NewTee` shouldn't be necessary.

**Comment by bearcherian** [comment]
I came across this issue on a Google search trying to do the same thing. The links posted above have changed, as the uber-go/fx project has changed a lot. The correct links to what I believe is the state of the files when this issue was originally commented on are below.
* https://github.com/uber-go/fx/blob/936b4a86043af92e15c76ed529ff3168f2a04318/ulog/sentry/sentry.go
* https://github.com/uber-go/fx/blob/936b4a86043af92e15c76ed529ff3168f2a04318/ulog/log.go#L81
