### ISSUE TITLE
How to use AtomicLevel.ServeHTTP

### ISSUE THREAD

**Issue by djui** [uber-go/zap#437]
Once my config package instantiates a new `zap.Logger` it seems that I can't access the `AtomicLevel` anymore to use `.ServeHTTP`. Is this correct? Iff, I would have to first create my own `zap.AtomicLevel` and then create my new `zap.Logger` and then carry both around from my config to my server instantiation, which makes `zap.NewProduction` pretty much irrelevant.

Additionally, is there no way to inspect the `zap.Config` or a logger instance? `zap.Logger.Core()` does not seems to reveal that. With access to the `zap.Config`, one could get the `zap.AtomicLevel`.

**Comment by djui** [comment]
This seems to have the same root cause as https://github.com/uber-go/zap/issues/433.

**Comment by akshayjshah** [comment]
You're correct that you can't access AtomicLevel from a Logger, because not all loggers have an AtomicLevel - some have other implementations of the `LevelEnabler` interface. For the same reason, you can't access a Config from a Logger - not all Loggers come from Config.

Zap is built around the `zap.New` and `zapcore.NewCore` APIs. `zap.Config` removes some boilerplate from the *most common* way to use those APIs, and `zap.NewProduction` removes even more. That reduction in boilerplate comes with tradeoffs - with `zap.NewProduction`, you can't access the level's `ServeHTTP` method.

Like most folks, it sounds to me like you'll be best served by using `zap.Config`. Instantiate a config struct (possibly by reading from some config file or environment variables), and use that config to create a logger and serve the level-changing HTTP handler.

**Comment by djui** [comment]
Understood and makes sense. That's what I ended up.
