### ISSUE TITLE
non-nesting customizable marshaling for a type

### ISSUE THREAD

**Issue by tv42** [uber-go/zap#441]
Hi. Apologies if I just don't understand how to do this with zap, but it seems like this functionality is missing.

It seems `zapcore.ObjectMarshaler` can only be used by objects that have internal structure; for example, a struct that adds multiple fields to the log.

However, I often end up making a type for simpler things, like a request id: `type RequestID uint64`, and things don't work out as nicely.

I could use `enc.AddUint64("request", uint64(msg.RequestID))` in the parent, but frankly `RequestID` should be the only party that knows it's an `uint64` underneath, so I would like it to do its own log marshaling.

If I use `ObjectMarshaler` for that, I can't avoid introducing an extra level of nesting:

```json
$ go run main.go
{"level":"info","ts":1496619787.6029024,"caller":"zap-demo/main.go:27","msg":"demo","id":{"this is unnecessary":42}}
```

```go
package main

import (
	"log"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

type SomeID uint64

var _ zapcore.ObjectMarshaler = SomeID(0)

func (f SomeID) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddUint64("this is unnecessary", uint64(f))
	return nil
}

func main() {
	logger, err := zap.NewProduction()
	if err != nil {
		log.Fatalf("error setting up logging: %v", err)
	}

	logger.Info("demo",
		zap.Object("id", SomeID(42)),
	)
}
```

Right now, the best route I can see is something like

```go
func (id SomeID) Zap(key string) zapcore.Field {
    return zap.Uint64(key, uint64(id))
}
```

But that `key` sort of doesn't belong there, either. I could hardcode the key inside `SomeID`, but that sounds wrong -- what if I have two fields of that same type, with different semantics?

Maybe something like this would work:

```go
type ValueMarshaler interface {
    MarshalLogValue(ValueEncoder) error
}

type ValueEncoder interface {
    // call only one
    ...
    SetUint64(value uint64)
    ...
}
```
Any advice?

**Comment by akshayjshah** [comment]
Good question. Zap doesn't currently support anything like the `ValueMarshaler` interface you've suggested, so there's currently no way to make your `RequestID` serialize properly without knowing a little bit about the logger's encoding.

If you make the (probably reasonable) assumption that the logger's encoding is text-based rather than binary, you can accomplish something similar using the standard library's interfaces. Have your `RequestID` type implement `json.Marshaler` or `encoding.TextMarshaler`, and it'll be logged properly when passed to a JSON-formatting logger via `zap.Any`.
