### ISSUE TITLE
Why is it so fast?

### ISSUE THREAD

**Issue by blitzprog** [uber-go/zap#447]
Is there an explanation of the source code?
I am currently reading it but haven't found anything interesting yet.

What exactly makes zap faster than simply creating pooled `bytes.Buffer` objects and then logging via `file.Write(buffer.Bytes())` using a mutex for multi-threaded file access?

I am honestly really impressed by the performance.

**Comment by akshayjshah** [comment]
Sorry the delayed response! Zap writes to files using exactly the approach you've described, but the difficult part is producing the correct bytes in the first place. Put differently, zap solves the problem of converting `logger.Info("message", zap.String("foo", "bar"))` to `{"msg": "message", "foo":"bar"}`.

Most of zap's speed comes from incrementally encoding logs. Instead of accumulating fields as a `map[string]interface{}` and using `json.Marshal` to encode them just before writing to a file, zap serializes each field and passes around a `[]byte`. Basically, it memoizes serialization.

The remainder of the performance gains come from the `Field` type, which reduces allocations by avoiding passing values as `interface{}`.
