### ISSUE TITLE
How to implement a filtering middleware core?

### ISSUE THREAD

**Issue by tchap** [uber-go/zap#453]
Hi,

I implemented a core that sends log entries to Sentry. But I want to skip entries containing particular fields from being sent to Sentry. For that reason I tried to implement a core that would wrap the Sentry core and simply skip writing the entry when certain field is present.

The thing is, I don't see how the filtering core can be done in a generic way since calling `Check` on the filtering core should obviously call `Check` on the core being wrapped. But that will add the underlying core into the checked entry, causing it to always contain the log entry. In other words, this does not work:

https://github.com/tchap/zapext/blob/a5d992351555de581c6d36e2829287a6d1c2f16a/middleware/core_filtering.go

The problem seems to be that fields are not available in `Check` so I cannot run the filter function without really calling the underlying core's `Check` first.

Any ideas how to do this? Am I missing something obvious?

**Comment by akshayjshah** [comment]
@tchap This is a great question - I'm going to add it to the FAQ whenever I can free up the time to write decent docs (hopefully soon!).

You're right that `Core` doesn't have access to the fields. There's a simple reason for this - most of them have already been serialized into `[]byte`, and the core doesn't always know what the encoding is!

However, you should still be able to accomplish this. Rather than trying to do the filtering in `Check`, do it in `With` and `Write`. In `With`, you can inspect each of the fields - if any of them make you want to filter out the entry, `return zapcore.NewNopCore()`. In `Write`, do the same - look at the fields, and if any of them make you want to drop the log entry, short-circuit and `return nil`.

I suspect that this can actually be quite generic - if you have time, I'd love to see a PR that adds

```
zap.NewFilteringCore(filter func(Field) bool, core zapcore.Core) zapcore.Core
)
```

**Comment by tchap** [comment]
@akshayjshah I can send the PR in the evening or tomorrow, no problem.

I would personally swap the arguments, i.e. I would make it

```golang
zap.NewFilteringCore(next zapcore.Core, filter func(Field) bool) zapcore.Core
```

But I will make it as you wish.

**Comment by tchap** [comment]
Also from the naming and signature we have chosen it may seem that the core is just filtering fields and then sending the entry containing the fields not filtered out. I will think about a better naming.

**Comment by tchap** [comment]
Perhaps we could add `EntryFilteringCore` and `FieldFilteringCore` separately.

```golang
zap.NewEntryFilteringCore(next zapcore.Core, filter func(Field) bool) zapcore.Core
zap.NewFieldFilteringCore(next zapcore.Core, filter func(Field) bool) zapcore.Core
```

**Comment by akshayjshah** [comment]
Sure, sounds good.

**Comment by tchap** [comment]
@akshayjshah This does not seem to be working, the test is failing: 

https://github.com/tchap/zap/commit/9a7e9cb979241e41d857d2a8a5bd8d5fb45d0c87

What am I doing wrong?

**Comment by tchap** [comment]
Ok, I see where the problem is...

**Comment by tchap** [comment]
Actually I don't :-) 

https://github.com/tchap/zap/commit/10dbb7923af5656099a40880e8ebd09e8f058bb9

This doesn't work either. Anyway, I guess that I will open a pull request and we can discuss there...

**Comment by akshayjshah** [comment]
Discussed on the PR; after looking more carefully, it's possible to do this reasonably well, but not in a way that can wrap *any* `zapcore.Core` implementation. Since it's not possible to make it fully generic, I've recommended that @tchap take the code he wrote (which is quite nice, and works well with all of zap's built-in `Core` types) and put it into an extension package or into the project that needs it.
