### ISSUE TITLE
when log file was deleted, what should to do?

### ISSUE THREAD

**Issue by neoduan** [uber-go/zap#480]
hey ,
by zap，i put log into a file , but the file was deleted，log info will be miss~~what should i to do？

**Comment by arthurkiller** [comment]
@neoduan  Should not delete the file. FD will continue writting till you exit, the resource will be released

**Comment by arthurkiller** [comment]
This is your mistake not the logger

**Comment by akshayjshah** [comment]
@arthurkiller Thanks for jumping in! I've been unfortunately busy and didn't have a chance to reply. Please try to be constructive, though - let's build a community that's friendly and welcoming here.

@neoduan, this isn't a problem that zap solves automatically. You can implement `zapcore.WriteSyncer` yourself, which will let you handle cases where the file disappears - for example, you could recreate the file as necessary.

Zap doesn't handle this by default because, in our view, deleting log files while the process is still writing to them is a problem that human operators should debug and fix.

**Comment by neoduan** [comment]
@akshayjshah thanks for your answer.
