### ISSUE TITLE
Custom timestamp field

### ISSUE THREAD

**Issue by apremalal** [uber-go/zap#485]
I'm trying to customise the time stamp field as mentioned in the last comment of this thread.

https://github.com/uber-go/zap/issues/33

```
logger := zap.New(
  zap.NewJSONEncoder(zap.RFC3339Formatter("@timestamp")),
  zap.ErrorLevel,
  zap.Output(someFile),
)
```

But it seems the content is outdated already. I couldn't locate `zap.RFC3339Formatter`  and `zap.NewJSONEncoder` is moved to `zapcore.NewJSONEncoder`. An example usage with the new API changes would be a great thing to have.

**Comment by akshayjshah** [comment]
Those APIs are all extremely outdated - they predate zap's 1.0 release.

Try starting with the [current GoDoc](https://godoc.org/go.uber.org/zap) instead.

**Comment by apremalal** [comment]
Not enough documentation on timestamp usage. I've moved to a different logging library. Thanks.

**Comment by akshayjshah** [comment]
Cool - best of luck!

**Comment by dmuntean** [comment]
For the sake of those who come to this issue trying to configure a custom timestamp, here is an example of how to do it with current API:

	atom := zap.NewAtomicLevel()

	encoderCfg := zap.NewProductionEncoderConfig()
	encoderCfg.TimeKey = "timestamp"
	encoderCfg.EncodeTime = zapcore.ISO8601TimeEncoder

	logger := zap.New(zapcore.NewCore(
		zapcore.NewJSONEncoder(encoderCfg),
		zapcore.Lock(os.Stdout),
		atom,
	))

	defer logger.Sync()

	atom.SetLevel(zap.DebugLevel)

**Comment by grosser** [comment]
FYI smaller way of doing a custom config:
```go
loggerConfig := zap.NewProductionConfig()
loggerConfig.EncoderConfig.TimeKey = "timestamp"
logger, err := loggerConfig.Build()
```

**Comment by gopaltirupur** [comment]
https://blog.sandipb.net/2018/05/03/using-zap-creating-custom-encoders/

**Comment by lengthmin** [comment]
use a human-readable time format:
```go
var cfg zap.Config = zap.NewProductionConfig()
// cfg.OutputPaths = []string{"judger.log"}
cfg.EncoderConfig.EncodeTime = zapcore.RFC3339TimeEncoder

logger, err := cfg.Build()
```

**Comment by happybydefault** [comment]
I think this is the best way, as you can use any Go time layout string you want:

```golang
config := zap.NewProductionConfig() // or zap.NewDevelopmentConfig() or any other zap.Config
config.EncoderConfig.EncodeTime = zapcore.TimeEncoderOfLayout(time.RFC3339) // or time.RubyDate or "2006-01-02 15:04:05" or even freaking time.Kitchen

logger, err := config.Build()
```

**Comment by rking-bennie** [comment]
I appreciate you all following up on this thread. TBH I almost left zap as well because I thought this should be simple and virtually every top google link was not helpful. I would assume that everyone who looks to use your framework wants to do this since the default is not that helpful. I would recommend maybe putting this simple example in your README. I've used several framework across several different languages and pretty new to Go but it was painful to finally find this post with the answer i needed

**Comment by sywhang** [comment]
@rking-bennie thank you for the feedback. Appreciate the patience and apologies for the difficulties you ran into. 

Couple of things:
1. I'll turn this thread into a discussion so that it can be more easily discovered.
2. We are discussing internally to gather effort for creating a documentation site that goes over core concepts and HOWTOs for some of the core open sourced frameworks and libraries, and Zap is on top of the mind for us. We will keep you updated via discussions announcement when that effort gets consolidated.

Thanks.
