### ISSUE TITLE
Consider exposing internal/exit

### ISSUE THREAD

**Issue by delicb** [uber-go/zap#494]
`Fatal` level exits application. It is not very convenient to test code that is using this, for anything other then simple command line applications (in which case test can use `os.Exec` to spawn new process with some arguments and verify that that process has exited). When testing function that has a branch that calls `log.Fatal`, tests will be interrupted.

Suggestion is to move `internal/exit` to `zaptest/exit`. This would allow users of `zap` to write their own tests that are using `zap.Fatal`.

What do you think? Are there any downsides for doing this? I might provide PR if this turns out to be acceptable.

**Comment by akshayjshah** [comment]
I'd prefer not to expose these APIs: not only do I not want to commit to them, they modify package-global state in a way that's not safe for general use.

In general, I agree that testing calls to `Fatal` is difficult. Rather than making testing easier, I'd encourage you to *only* use `Fatal` in `main`. Everywhere else, use `DPanic` and below.

**Comment by delicb** [comment]
I totally agree that `Fatal` should not be used anywhere except one place (entry point of application). However, I have kind of a wrapper around zap that does few more things that zap does not do (which are specific to my needs). So, in order to test my library, I would need a way to mock exit. Since it is quite hard to do, I was happy to find out that it is already done in zap, but it turned out that I can not use it. Hence - this ticket.

I understand that you do not want to commit to this API.

Do you maybe have other suggestions how I might approach this problem? It can be either on my or zap side. I would be happy to discuss them and potentially implement it. If not - feel free to close this ticket. 

Thanks.

**Comment by akshayjshah** [comment]
I'm reluctant to expose this API because it modifies global state. This makes it really easy for one package to corrupt zap's state for all other users.

In your code, I'd suggest doing exactly what zap does - make all calls to `zap.Fatal` through a layer of indirection, so that you can test your use of zap's APIs without actually crashing the process. Go's interfaces are a good fit for this - in your structs, depend on an interface you control that includes only the zap.Logger methods that you actually use.
