### ISSUE TITLE
gRPC Logger Not Using Pre-configured Settings

### ISSUE THREAD

**Issue by frankgreco** [uber-go/zap#511]
The following code can be found at: 
https://github.com/uber-go/zap/blob/master/zapgrpc/zapgrpc.go#L49-L61

```go
func NewLogger(l *zap.Logger, options ...Option) *Logger {
	logger := &Logger{
		log:    l.Sugar(),
		fatal:  (*zap.SugaredLogger).Fatal,
		fatalf: (*zap.SugaredLogger).Fatalf,
		print:  (*zap.SugaredLogger).Info,
		printf: (*zap.SugaredLogger).Infof,
	}
	for _, option := range options {
		option.apply(logger)
	}
	return logger
}
```

Since this function accepts a logger as a parameter, i'd expect it to use all of the configuration settings that that logger already has configured. But the code above isn't really leveraging that at all.

I'd love to discuss the reasons why this is implemented this way as opposed to using the configuration settings that the logger parameter already has configured.

A good use case is that in my code, I already inherit a logger that has fields that provide certain correlation ids and other means of providing context. If this logger used the logger that I passed in, that context would be maintained.

**Comment by akshayjshah** [comment]
This code is a bit tricky, but it *does* use all the logger's configuration.

`(*zap.SugaredLogger).Fatal` is a function pointer that takes the method's receiver as the first argument; if you look at the [gRPC logger's Fatal method's implementation](https://github.com/uber-go/zap/blob/master/zapgrpc/zapgrpc.go#L73), you'll see that we're passing the wrapped logger to the function. This has the same result as calling the `Fatal` method on the logger instance directly. Try it and see - wrapping `zap.NewProduction()` and `zap.NewDevelopment()` will produce very different output!

We do this because it makes some types of testing simpler, since we can supply alternate implementations of these functions.
