### ISSUE TITLE
Expose callerSkipOffset in Config

### ISSUE THREAD

**Issue by frankietaylor** [uber-go/zap#531]
Please expose callerSkipOffset in Config. Currently its hardcoded to 2. This is useful in cases where there is a logger wrapper through which all logging goes through. With the current code, all log lines are printing logger wrapper file name.

**Comment by akshayjshah** [comment]
We've avoided exposing this in config because the number of wrappers often changes at runtime (especially if you're often wrapping and unwrapping loggers to satisfy different interfaces). Instead, we've exposed this functionality via the [`AddCallerSkip` option](https://godoc.org/go.uber.org/zap#AddCallerSkip), which you can pass to any logger's [`WithOptions` method](https://godoc.org/go.uber.org/zap#Logger.WithOptions) to increase or decrease the skip level.

Using that option wherever you're wrapping zap should resolve this issue.
