### ISSUE TITLE
Creating a new zapcore Encoder might be a little hard

### ISSUE THREAD

**Issue by rhymes** [uber-go/zap#563]
So, I'm a Go newbie and I'm sure that's one of the reasons why it took me forever to create a new logging format. I wanted to configure my logging (that went well) and create a console encoder to output a format like: 

```
level=info time=2018-03-16T18:26:38Z caller=logging/logger.go:71 msg="test message" key=value key2=value2
```

I managed to do it but it has been quite a journey. 

I basically copied and pasted https://github.com/uber-go/zap/blob/master/zapcore/json_encoder.go and then adapted it. 

I created a gist for it https://gist.github.com/rhymes/1603940e5ab9ef7860d67f4abd70d407

Here are the higlights:

I created global buffer pool like this:

```go
var bufferPool = buffer.NewPool()
```

instead of the "internal/bufferpool" the json encoder uses.

`addKey` and `addElementSeparator` have been changed to:

```go
func (enc *kvEncoder) addKey(key string) {
	enc.buf.AppendString(key)
	enc.buf.AppendByte('=')
}

func (enc *kvEncoder) addElementSeparator() {
	enc.buf.AppendByte(' ')
}
```

Finally I add to slightly change addKeys because it wasn't exported and I had troubles with the interfaces:

```go
func addFields(kvEnc *kvEncoder, enc zapcore.ObjectEncoder, fields []zapcore.Field) {
	for i := range fields {
		fields[i].AddTo(enc)
		kvEnc.buf.AppendByte(' ')
	}
}
```

The rest is more or less the same apart from the adaptations to make the file work outside zapcore's package.

You can just use it with:

```go
func keyValueEncoder(c zapcore.EncoderConfig) (zapcore.Encoder, error) {
	return NewKVEncoder(c), nil
}
zap.RegisterEncoder("key-value", keyValueEncoder)
```

Again, this is the output:

```
level=info time=2018-03-16T18:39:08Z caller=logging/logger.go:71 msg="test message" key=value key2=value2
```

* I have no idea if this stuff is correct or safe :-)
* I understand why the internal implementation is so complicated, it's just hard to create a new encoder for users of the library API
* This is definitely copy and paste programming
* It has been a hell of a journey for someone who's been writing Go code for just a few days :D

Any help on how to simplify it? 

Thanks

**Comment by akshayjshah** [comment]
Sorry for the late reply! You're definitely right - creating a new encoder from scratch takes a fair bit of work.

First, you may want to take a look at #570 - we actually had an encoding a lot like what you've laid out, and we ended up concluding that it wasn't particularly useful (at least to us).

However, I can see why you might want something like this (after all, we gave it a try too). The JSON encoder is long and finicky because it's what we run in production, so it's worth hand-optimizing every allocation. If you're only using the text encoder during development (and don't care about performance), you can do something much simpler: implement `zapcore.Encoder` by embedding the JSON encoder. That gives you all of `zapcore.ObjectEncoder` for free. Then, you'll implement `Clone` and `EncodeEntry` yourself. `Clone` just calls `Clone` on the embedded JSON encoder and re-wraps it in your new encoder struct. `EncodeEntry` can call the JSON encoder's `EncodeEntry` method, then unmarshal the JSON into a `map[string]interface{}`. From there, you can serialize the message however you'd like.

That'll be much, much easier to implement, but you'll pay a performance cost during the unmarshal-and-remarshal step.

**Comment by rhymes** [comment]
@akshayjshah thanks!
