### ISSUE TITLE
Missing text encoder

### ISSUE THREAD

**Issue by raytung** [uber-go/zap#570]
Hey all,

As I was looking for a non-JSON encoder for local development, I came across issue #59 as well as merge request #123 and saw there was actually a text encoder sometime back but it no longer exists in the project.

We probably forgot to move text encoder during the `zapcore` package migration (6bd8382, 5c9ffae).

Is there any plans to introduce text encoder back into the package?

**Comment by tnngo** [comment]
I think you didn't at the document carefully

**Comment by akshayjshah** [comment]
No - it wasn't forgotten, it was dropped.

Zap exposes *all* the functionality of JSON, YAML, and similar full-featured encodings. That means that objects in log messages can be nested arbitrarily deep. Since this is a structured logging library, I assume that many users are sending the output to something like ElasticSearch or Solr, which encourages this kind of nesting to avoid type collisions.

The ad-hoc text encoding I cooked up in the pre-1.0 days had a *lot* of trouble sanely representing nested objects. How should it serialize a `map[string][]map[int]string`? Solving those problems while keeping the output even sort of readable amounted to reinventing JSON (or TOML, or YAML, or whatever). After looking at the result, JSON turned out to be more compact and more readable.

If you're still interested in a more freeform text encoding, you can definitely ship it as a third-party package and integrate with zap via `zap.RegisterEncoder`.

**Comment by raytung** [comment]
Cheers, thanks for the explanation! @akshayjshah
