### ISSUE TITLE
Check vs Enabled

### ISSUE THREAD

**Issue by djui** [uber-go/zap#582]
Less of an issue than rather a question: When would someone use one or the other?

```go
if l := logger.Check(zap.DebugLevel, "message"); l != nil {
    outcome := heavyWork()
    l.Write(zap.Any("outcome", outcome))
}
```

vs

```go
if logger.Core().Enabled(zapcore.DebugLevel) {
    outcome := heavyWork()
    logger.Debug("message", zap.Any("outcome", outcome))
}
```

**Comment by prashantv** [comment]
`Enabled` tells you whether the logger level will ever allow that level to be logged. `Check` allows features like sampling (see the [Sampling core](https://godoc.org/go.uber.org/zap/zapcore#NewSampler)) to skip log messages, even if that level is enabled.

In practice, you should use `Check` when deciding whether to log a message for a couple of reasons:
 * It returns `false` if sampling decides to skip a log (because this message has already been logged frequently in the past second or whatever time window you've chosen), skipping the allocations for the fields.
 * It avoids duplicationg of the level -- `Enabled` requires you to pass the level to the `Enabled` function as well as specifying it again when calling the method on `logger`.

**Comment by djui** [comment]
Thanks! Good points and clean explanation.

**Comment by siraj-mansour-deltatre** [comment]
> `Enabled` tells you whether the logger level will ever allow that level to be logged. `Check` allows features like sampling (see the [Sampling core](https://godoc.org/go.uber.org/zap/zapcore#NewSampler)) to skip log messages, even if that level is enabled.
> 
> In practice, you should use `Check` when deciding whether to log a message for a couple of reasons:
> 
> * It returns `false` if sampling decides to skip a log (because this message has already been logged frequently in the past second or whatever time window you've chosen), skipping the allocations for the fields.
> * It avoids duplicationg of the level -- `Enabled` requires you to pass the level to the `Enabled` function as well as specifying it again when calling the method on `logger`.

Quick correction :
Check returns a `CheckedEntry` if an entry will be logged, or `nil` if not.
