### ISSUE TITLE
How to change logging level at run time at childlogger and its descendants but leave parent logger alone?

### ISSUE THREAD

**Issue by etsangsplk** [uber-go/zap#591]
logger is the parent logger and childlogger derives from logger.
as you see the childlogger inherits the logger settings in 1st half of example.
But when try to change the logger in 2nd half of example, the changes are not kept and childlogger does not get inherit the new settings either. 

Notice that:
logger is not changed nor settings being passed down to descendants from childlogger.
I know WithOptions is cloning so probably not the right api call, but not seeing others or straight forward way to do it.

```go
	cfg := zap.Config{
		Encoding:         "json",
		Level:            zap.NewAtomicLevelAt(zapcore.DebugLevel),
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
		EncoderConfig: zapcore.EncoderConfig{
			MessageKey: "message",

			LevelKey:    "level",
			EncodeLevel: zapcore.CapitalLevelEncoder,

			TimeKey:    "time",
			EncodeTime: zapcore.ISO8601TimeEncoder,

			CallerKey:    "caller",
			EncodeCaller: zapcore.ShortCallerEncoder,
		},
	}
	logger, _ = cfg.Build()
        childlogger := logger.With(zap.String("logger", "child generation 1"))

	logger.Debug("This is a DEBUG message")
	logger.Info("This is an INFO message")
	logger.Info("This is an INFO message with fields", zap.String("region", "us-west"), zap.Int("id", 2))
     // 
     childlogger.Debug("This is a DEBUG message from child logger") 
     childlogger.Info("This is an INFO message from child logger") 
     // try to change the parent logger
	logger.WithOptions(
		zap.WrapCore(
			func(zapcore.Core) zapcore.Core {
				return zapcore.NewCore(zapcore.NewConsoleEncoder(cfg.EncoderConfig), zapcore.AddSync(os.Stderr), zapcore.InfoLevel)
			})).Debug("This is a DEBUG message, but should not be printed")
    logger.Debug("This is a DEBUG message, but should not be printed") 
    // try to change jsut the child logger
    childlogger.WithOptions(
        zap.WrapCore(
            func(zapcore.Core) zapcore.Core {
                return zapcore.NewCore(zapcore.NewConsoleEncoder(cfg.EncoderConfig), zapcore.AddSync(os.Stderr), zapcore.InfoLevel)
            })).Debug("This is a DEBUG message, but should not be printed")

    logger.Debug("This is a DEBUG message, but should not printed") 

    childlogger.Debug("This is a DEBUG message from child logger, should not be printed") 
    childlogger.Info("This is an INFO message from child logger") 
    childlogger2.Debug("This is a DEBUG message from child logger2, should not be printed") 
    childlogger2.Info("This is an INFO message from child logger2")

```

Output:
```
** Same logger with console logging enabled instead with Info level now

{"level":"DEBUG","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:108","message":"This is a DEBUG message, but should not be printed"}
{"level":"DEBUG","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:116","message":"This is a DEBUG message, but should not printed"}
{"level":"DEBUG","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:118","message":"This is a DEBUG message from child logger, should not be printed","logger":"child generation 1"}
{"level":"INFO","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:119","message":"This is an INFO message from child logger","logger":"child generation 1"}
{"level":"DEBUG","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:120","message":"This is a DEBUG message from child logger2, should not be printed","logger":"child generation 1","logger":"child generation 2"}
{"level":"INFO","time":"2018-05-16T15:01:19.842-0700","caller":"customlogger/main.go:121","message":"This is an INFO message from child logger2","logger":"child generation 1","logger":"child generation 2"}
```

**Comment by etsangsplk** [comment]
more example:
Note that setting logger does not propagate to childlogger 2

```
	logger, _ := zap.Config{
		Encoding:    "json",
		Level:       zap.NewAtomicLevelAt(zapcore.DebugLevel),
		OutputPaths: []string{"stdout"},
	}.Build()

	fmt.Printf("\n*** Using a JSON encoder, at debug level, sending output to stdout, all possible keys specified\n\n")

	cfg := zap.Config{
		Encoding:         "json",
		Level:            zap.NewAtomicLevelAt(zapcore.InfoLevel),
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
		EncoderConfig: zapcore.EncoderConfig{
			MessageKey: "message",

			LevelKey:    "level",
			EncodeLevel: zapcore.CapitalLevelEncoder,

			TimeKey:    "time",
			EncodeTime: zapcore.ISO8601TimeEncoder,

			CallerKey:    "caller",
			EncodeCaller: zapcore.ShortCallerEncoder,
		},
	}
	logger, _ = cfg.Build()
	childlogger := logger.With(zap.String("logger", "child generation 1"))
	childlogger2 := childlogger.With(zap.String("logger", "child generation 2"))

	logger.Debug("This is a DEBUG message should not be printed")
	logger.Info("This is an INFO message")
	logger.Info("This is an INFO message with fields", zap.String("region", "us-west"), zap.Int("id", 2))

	childlogger.Debug("This is a DEBUG message from child logger should not be printed")
	childlogger.Info("This is an INFO message from child logger")

	childlogger2.Debug("This is a DEBUG message from child logger2 should not be printed")
	childlogger2.Info("This is an INFO message from child logger2")

	fmt.Printf("\n*** Same logger with console logging enabled instead with Info level now\n\n")

	logger.WithOptions(
		zap.WrapCore(
			func(zapcore.Core) zapcore.Core {
				return zapcore.NewCore(zapcore.NewConsoleEncoder(cfg.EncoderConfig), zapcore.AddSync(os.Stderr), zapcore.InfoLevel)
			})).Debug("This is a DEBUG message, but should not be printed")
	logger.Debug("This is a DEBUG message, but should not be printed")
    logger.Info("This is a INFO message")
	childlogger.WithOptions(
		zap.WrapCore(
			func(zapcore.Core) zapcore.Core {
				return zapcore.NewCore(zapcore.NewConsoleEncoder(cfg.EncoderConfig), zapcore.AddSync(os.Stderr), zapcore.ErrorLevel)
			})).Debug("This is a DEBUG message, but should not be printed")

	logger.Debug("This is a DEBUG message, but should not printed")
    logger.Info("This is a INFO message should be printed")
	childlogger.Debug("This is a DEBUG message from child logger, should not be printed")
	childlogger.Info("This is an INFO message from child logger")
	childlogger2.Debug("This is a DEBUG message from child logger2, should not be printed")
	childlogger2.Info("This is an INFO message from child logger2")

    logger.WithOptions(
        zap.WrapCore(
            func(zapcore.Core) zapcore.Core {
                return zapcore.NewCore(zapcore.NewConsoleEncoder(cfg.EncoderConfig), zapcore.AddSync(os.Stderr), zapcore.ErrorLevel)
            })).Debug("This is a DEBUG message, but should not be printed")

    childlogger.Debug("This is a DEBUG message from child logger, should not be printed")
    childlogger.Info("This is an INFO message from child logger, should not be printed")

    childlogger2.Debug("This is a DEBUG message from child logger2, should not be printed")
    childlogger2.Info("This is an INFO message from child logger2, should not be printed")   
```
Output:
Note that setting logger does not propagate to childlogger 2
```
*** Using a JSON encoder, at debug level, sending output to stdout, all possible keys specified

{"level":"INFO","time":"2018-05-16T15:59:09.920-0700","caller":"customlogger/main.go:73","message":"This is an INFO message"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:74","message":"This is an INFO message with fields","region":"us-west","id":2}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:77","message":"This is an INFO message from child logger","logger":"child generation 1"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:80","message":"This is an INFO message from child logger2","logger":"child generation 1","logger":"child generation 2"}

*** Same logger with console logging enabled instead with Info level now

{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:90","message":"This is a INFO message"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:98","message":"This is a INFO message should be printed"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:100","message":"This is an INFO message from child logger","logger":"child generation 1"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:102","message":"This is an INFO message from child logger2","logger":"child generation 1","logger":"child generation 2"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:111","message":"This is an INFO message from child logger, should not be printed","logger":"child generation 1"}
{"level":"INFO","time":"2018-05-16T15:59:09.921-0700","caller":"customlogger/main.go:114","message":"This is an INFO message from child logger2, should not be printed","logger":"child generation 1","logger":"child generation 2"}
```

**Comment by billf** [comment]
https://godoc.org/go.uber.org/zap#Logger.WithOptions
> WithOptions clones the current Logger, applies the supplied Options, and returns the resulting Logger.

`(*zap.Logger).WithOptions` is _not_ an in-place modification of a logger.

In the provided code, the "child loggers" are created:
```go
childlogger := logger.With(zap.String("logger", "child generation 1"))
childlogger2 := childlogger.With(zap.String("logger", "child generation 2"))
```

Your calls to `(*zap.Logger).WithOptions` that have a different level work as you expect, but only _when the return value is used_:

```go
 logger.WithOptions(
        zap.WrapCore(zapcore.ErrorLevel)).Info("this will be thrown away")
```

The `(*zap.Logger)` value of `childlogger` are `childlogger2` are never **overwritten**.
Overwrite `childlogger` with the cloned logger with new options:

```go
childlogger = childlogger.WithOptions(zap.WrapCore(
  func(zapcore.Core) zapcore.Core {
    return zapcore.NewCore(/*....*/, zapcore.ErrorLevel)
  }))
```

Take a look at the examples in [zap.AtomicLevel](https://godoc.org/go.uber.org/zap#AtomicLevel). If you clone `childlogger` with an `zap.AtomicLevel` that you keep a reference to, you should be able to change the child logger and each descendent with a single call to [(*zap.AtomicLevel).SetLevel](https://godoc.org/go.uber.org/zap#AtomicLevel.SetLevel).

**Comment by etsangsplk** [comment]
@billf 
Possible to extract the underlying Encoder and WriteSyncer from the old core?
My example assumes that I can have access to the config. but in reality childlogger should have everything it's parent has. It does not look like there are apis to return whats underneath.

**Comment by cstockton** [comment]
@billf Is there a way to obtain the current encoder? I am having trouble figuring out a way to solve a fairly simple use case: mask `Info` level messages in a really noisy 3rd party package by setting a new log level for the child logger. The offending package accepts a `*zap.Logger` but I can not figure out a way to take the current `*zap.Logger` and derive an identical logger with a new level. As I believe @etsangsplk mentioned the API does not provide a way to extract the configuration used for the current `zap.Core`. Since logger configuration is one of the first things my app does during initialization the config for it is long gone.

I think contextual log levels is a pretty basic / fair use case, how do you feel about adding a `zap.WithLevel` option for this?

**Comment by prashantv** [comment]
The code snippet in @billf's comment lets you create a logger that has a higher log level (e.g., if your current logger is `Info`, you can create a new logger that only logs `Error` or higher).

While this could be made easier, I think a `WithLevel` might cause confusion since it doesn't allow the level to be lowered, only increased.

**Comment by cstockton** [comment]
@prashantv The code snippet is missing the important bit, constructing a new core. Currently it's impossible (as far as I can tell) to reuse the existing core without implementing a core yourself, the bit the example snippet left out. This means that where you want to clone your logger you need to propagate the configuration bits needed to build it from scratch.

```Go
childlogger = childlogger.WithOptions(zap.WrapCore(
  func(zapcore.Core) zapcore.Core {
    return zapcore.NewCore(
      childLogger.Encoder, // no way to access the current encoder to clone it AFAIK
      childLogger.WriteSyncer, // Likewise.
      zapcore.ErrorLevel)
  }))
```

In addition the constraint to not be able to lower the log level of a child logger seems like an arbitrary constraint at best, and inconsistent at worst. Consider the With and WithOptions methods:
```Go
// With creates a child logger and adds structured context to it. Fields added to the child don't affect the parent, and vice versa.
func (log *Logger) With(fields ...Field) *Logger

// WithOptions clones the current Logger, applies the supplied Options, and returns the resulting Logger. It's safe to use concurrently. 
func (log *Logger) WithOptions(opts ...Option) *Logger
```

Child loggers created via `With` do not observe newly added fields to parent, `WithOptions` claims to clone the existing logger. The LevelEnabler interface is an option to `zapcore.NewCore` and is embedded in zapcore.Core with no indication it's hierarchical, just like Encoder and the Config. I would not expect every single parent `zapcore.LevelEnabler` interface to be invoked in a child logger anymore than I would expect the WriteSyncer or Encoder to be called. In fact I don't really see how it could work that way- since zap.NewCore() does not take an existing core to form a tree of previous cores to call.

In short, this feels like it's easily fixable and would be consistent and intuitive with the existing API:
```Go
// Most concise with minimal surface area:
child := lr.WithOptions(zap.WithLeveler(zapcore.ErrorLevel))
```

WithLeveler could also clarify that it replaces the existing leveler, since the LevelEnabler is a one method interface it's much simpler for a user to write one that only allows raising an enabler:
```Go
core := lr.Core()
child := lr.WithOptions(zap.WithLeveler(
	zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return zapcore.ErrorLevel.Enabled(lvl) && core.Enabled(lvl)
	}),
))
```

Alternatively, accept multiple levelers in WithLeveler - documenting they will be AND together to get the raising behavior with minimal user effort with the same API surface:
```
child := lr.WithOptions(zap.WithLeveler(lr.Core(), zapcore.ErrorLevel)
```

Would a pull request be considered for any of these options?

**Comment by prashantv** [comment]
You are right that the `WrapCode` can't be used with `NewCore`, but that you would need to provide a core adapter which filters out new logs as part of `LevelEnabler` *and* `Check`.

> In addition the constraint to not be able to lower the log level of a child logger seems like an arbitrary constraint at best, and inconsistent at worst. Consider the With and WithOptions methods:

I'm not making up a constraint here -- I'm letting you know what's possible given the API of `Core`.

`Core` is an interface and can be implemented by anyone ([example](https://github.com/uber-common/bark/blob/master/zbark/zapify.go#L51)). Even if you replace the `LevelEnabler`, the `Check` method will still check the passed in entry's level against the internal level of the `Core` implementation.

Given that constraint, I don't think it's possible to force an underlying core implementation to log more than it was configured to log since `Core` is an arbitrary interface, and an implementation of `Core` might have hardcoded to only log calls that are `Error` or higher.

**Comment by cstockton** [comment]
I'm not following you @prashantv, I'm sorry. My take away from the below:

> The code snippet in @billf's comment lets you create a logger that has a higher log level (e.g., if your current logger is Info, you can create a new logger that only logs Error or higher).
> While this could be made easier, I think a WithLevel might cause confusion since it doesn't allow the level to be lowered, only increased.

Was that the proposed `WithLeveler` could not allow a way to lower the log level. The entirety of my response was more or less trying to come to an understanding of how that would be the case. I don't see how the implementation of zapcore.Core could add such a constraint.

 I made a proposal because I think discussing an implementation may bring us in sync. Thanks for the response.

**Comment by roppa** [comment]
I'm new to Zap. I'm creating a logger with the option to use kafka. I've got that part working, but we also want to be able to run in debug mode when developing locally, but log only >= info in production. I've been looking for ages and can't find any examples. My code is below:

```golang
// zap monitors and samples logs.
// See advanced config example: https://github.com/uber-go/zap/blob/master/example_test.go#L105
var lowPriority = zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
	return lvl < zapcore.ErrorLevel
})
var kafkaPriority = zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
	return lvl == zapcore.InfoLevel
})

// Init creates a new instance of a logger. Namespace is the name of the module using the logger. broker and topic are Kafa specific,
// if either of these is not set a default console logger is created.
func Init(namespace, broker, topic string) *Logger {
	// cores are logger interfaces
	var cores []zapcore.Core

	// optimise message for console output (human readable)
	consoleEncoder := zapcore.NewConsoleEncoder(zap.NewProductionEncoderConfig())
	// Lock wraps a WriteSyncer in a mutex to make it safe for concurrent use.
	// See https://godoc.org/go.uber.org/zap/zapcore

	cores = append(cores,
		zapcore.NewCore(consoleEncoder, zapcore.Lock(os.Stdout), lowPriority),
		zapcore.NewCore(consoleEncoder, zapcore.Lock(os.Stderr), zap.ErrorLevel),
	)

	useKafka := broker != "" && topic != ""
	if useKafka {
		cores = append(cores, getKafkaCore(broker, topic))
	}

	// join inputs, encoders, level-handling functions into cores, then "tee" together
	logger := zap.New(zapcore.NewTee(cores...))
	logger.Info("initiated logger", zap.String("namespace", namespace), zap.Bool("kafka", useKafka))
	defer logger.Sync()
	return &Logger{logger, namespace}
}

func getKafkaCore(broker, topic string) zapcore.Core {
	kafkaProducer, err := NewKafkaProducer(&KConfig{
		Broker: broker,
		Topic:  topic,
	})

	if err != nil {
		log.Fatal(err)
	}

	return zapcore.NewCore(
		zapcore.NewJSONEncoder(zap.NewProductionEncoderConfig()),
		zapcore.AddSync(kafkaProducer), kafkaPriority)
}
```
