### ISSUE TITLE
Wrap JSON encoder in custom encoder?

### ISSUE THREAD

**Issue by mrbanzai** [uber-go/zap#599]
I see several recommendations to simply wrap the JSON encoder when attempting to create a custom encoder (such as on #563) but, as that type doesn't seem to be exported, I'm a bit confused as to how that could be done?  My apologies if I'm overlooking something simple.

**Comment by mrbanzai** [comment]
I should elaborate that, in an attempt to simply embed a `Encoder` instantiated via `NewJSONEncoder`, I'm unable to call any of the `Encode*` methods on the configuration (`EncodeTime`, `EncodeDuration`, `EncodeLevel`, etc.) as `Encoder` does not implement `PrimitiveArrayEncoder` ... but the unexported `jsonEncoder` does.

**Comment by akshayjshah** [comment]
`Encoder` doesn't include all the methods of `ArrayEncoder`, because they don't make sense in that context - an `Encoder` only encodes objects, so it doesn't include methods that add elements to an array. However, you can always make a type assertion to expose the array-encoding API:

```
enc, _ := NewJSONEncoder(cfg)
arrayEncoder, ok := enc.(ArrayEncoder)
// make sure to handle failures here
```

Note that this cast isn't part of the backward-compatibility contract - you'll need to handle cases where the cast fails.

Also, the recommendations you've found (including #563) are *only* for quick-and-dirty encoder implementations. If you need full control over the output, or you're actually implementing a new encoding, you're better off writing an implementation from scratch.

**Comment by mrbanzai** [comment]
Thanks @akshayjshah I'll move forward with that advice!  My use case seemed like a pretty simple modification of the console encoder (using spaces instead of tabs as separators, due to issues when that output is piped out through logger, and displaying a particular field as part of the "message"), but it seemed more complicated to accomplish than I expected.
