### ISSUE TITLE
Data race detected?

### ISSUE THREAD

**Issue by MarcMagnin** [uber-go/zap#607]
Hi,
Thanks for this library!
I'm not entirely sure but it seems that this line can cause a data race:
https://github.com/uber-go/zap/blob/master/logger.go#L292

My data race output: 
```
WARNING: DATA RACE
Read at 0x00c420522088 by goroutine 193:
 ---/go.uber.org/zap.(*Logger).check()
     ---/vendor/go.uber.org/zap/logger.go:292 +0x216
  ---/vendor/go.uber.org/zap.(*Logger).Error()
     ---/vendor/go.uber.org/zap/logger.go:202 +0x55
  ---/components.(*Backup).Snapshot.func1()
     ---/components/backup.go:274 +0x8c1

Previous write at 0x00c420522088 by goroutine 26:
  [failed to restore the stack]
````

The backup.go:274 line:
`log.Error("request timed out")`

Regards

**Comment by MarcMagnin** [comment]
Thanks for your feedback.
I'm using lumberjack.v2. with  zapcore.AddSync(). Do you think that could be lumberjack then?

**Comment by akshayjshah** [comment]
I'm not familiar with the format of the data race output you've pasted in - it looks like you're using something to post-process the standard library's more verbose output. It's possible that the issue is in your WriteSyncer implementation, but I'm not familiar enough with lumberjack to debug further there.

It's certainly possible that there's a race somewhere in zap, but we use this package extensively internally and haven't encountered anything. If you can share a link to your code, it'd be easier to help you debug.

**Comment by prashantv** [comment]
I don't think this is an issue with a `WriteSyncer`, since the data race points to this line:
```go
	ce.ErrorOutput = log.errorOutput
```

The writer itself isn't called here. The only read I can see is `log.errorOutput`, but that field should be constant, it's set on construction of a logger. I don't see any code modifying it after returning a `*Logger` to the user.

Can you confirm that the version you are using is the latest release @MarcMagnin? Are you able to reproduce it, and able to get a full stack for the write that is racing with the read?

**Comment by akshayjshah** [comment]
Going to assume that this is unreproducible; if I'm wrong, please re-open!
