### ISSUE TITLE
zap.Duration encoding units question

### ISSUE THREAD

**Issue by hasryan** [uber-go/zap#649]
I have a question about the intended use of `zap.Duration`.  It appears that when using the default production logger and JSON encoder that these are output as a JSON number type (float) with units as a seconds.  The only way I have found to change this is by setting a logger-level configuration for the `EncoderConfig.EncodeDuration` to switch to nanos (`zapcore.NanosDurationEncoder`) or string (`zapcore.StringDurationEncoder`).

This isn't quite flexible enough for us because we frequently log durations in different units within our app.  Some we wish to log in milliseconds, others in seconds and less frequently in other units.  For this reason we have stopped using `zap.Duration` and instead convert our durations to floats / ints and then use the more basic field types like `zap.Float64` along with keys that describe the units i.e. "duration_millis"

Am I missing some more obvious way to utilize `zap.Duration` and specify units on a per-log basis?  My thought was that perhaps the `zap.Duration` constructor function would accept an additional arg which is the units to emit the value in, or to always use the "string" flavor so that units are part of the value itself, but this does not seem to be the case.

**Comment by elvinchan** [comment]
Any update on this ?

**Comment by abhinav** [comment]
Hello!

The EncodeDuration configuration in Zap changes how the logger encodes duration. As @icelynjennings pointed out, you can use that (with an existing or custom implementation) to change how durations are encoded in your logs.

We do not provide a means of changing how durations are logged on a per-log basis because that would add an unnecessary level of verbosity to the APIs. It is possible to specify a differently encoded duration at log sites by defining your own field constructors.

For example,

```go
func DurationMillis(name string, d time.Duration) zap.Field {
    return zap.Int64(name, d.Milliseconds())
}
```

```
zap.Info("msg",
    zap.Duration("foo", d),   // use default duration encoding
    DurationMillis("bar", d), // use millisecond duration encoding
)
```

Given that these custom field constructors are possible, we do not have plans to add support for a means of customizing how durations are encoded on a per log site basis.

@icelynjennings A PR to add something to the FAQ would be welcome!

Thanks!
