### ISSUE TITLE
Control log-level for packages without creating a new logger instance

### ISSUE THREAD

**Issue by ksvnsn** [uber-go/zap#658]
Hello,

Is there a way I can control log-level at a package level? I understand I can do this by creating a child logger in the package, but since child logger actually clones the existing logger, looks like it's a new instance altogether. I do not want to create a new instance of logger for every package.
Could you please let me know if there is a way to do this?

Thank you!

**Comment by akshayjshah** [comment]
By design, zap isn't a hierarchical logger (as is common in Java and Python) - you can create child loggers to add structured context to your logs, but you can't control log level on a per-logger or per-package basis.

I'm not aware of any Go logging packages that take a Java-style hierarchical approach. (That doesn't mean they're not out there, it just means that I don't have any experience with them.)

**Comment by ansel1** [comment]
Check out github.com/gemalto/flume. It uses zap as a core, but allows reconfiguring loggers by name. Useful for configuring the levels of all loggers from main().

**Comment by akshayjshah** [comment]
Cool! I haven't seen that package before, good to know. @ksvnsn, flume may fit your needs better.
