### ISSUE TITLE
zaptest does not mark a test as failed on error

### ISSUE THREAD

**Issue by nhooyr** [uber-go/zap#677]
```
	zapl := zaptest.NewLogger(t)
	zapl.Info("xd")
	zapl.Error("xd")
```

Just run that with a test under zaptest. It won't be marked as failed.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by abhinav** [comment]
Oops, sorry, yeah, this is by design. The purpose of `zaptest.NewLogger` is
to capture logs from components that need to log values rather than log them
to stdout/stderr. This way, the logs show only if the test fails.

Logging an error-level message isn't necessarily cause for test failure. In
fact, often it won't be that because it's common for components to log
specifically in case of a failure that was handled; so if you're testing that,
you don't want your test to fail because of an intended error.
