### ISSUE TITLE
Would like negative version of AddCaller

### ISSUE THREAD

**Issue by danielbprice** [uber-go/zap#702]
If I have a logger and I need to derive a child logger which has the caller disabled, there doesn't seem to be a way to do it.

I had hoped to do something like:
```
child := parent.WithOptions(zap.DisableCaller())
```

**Comment by abhinav** [comment]
This seems like a reasonable ask.

My preference would have been for `AddCaller()` to accept a boolean argument
rather than being a switch in one direction.

    zap.AddCaller(true)
    zap.AddCaller(false)
    
Unfortunately, it's too late to change that API so adding a new option makes
sense.

As for the name, I would prefer AddCallerDisable because of godoc
discoverability (it'll show up next to AddCaller and AddCallerSkip) but I'd
like to hear what others think about this.

CC @jcorbin @prashantv

**Comment by prashantv** [comment]
Seems reasonable to add an option to disable it (we may want to same thing for other similar options like `Development`).

As a short-term workaround, I think you can achieve this using [`WrapCore`](https://godoc.org/go.uber.org/zap#WrapCore) to return a core that just drops the `Caller` field in [`Entry`](https://godoc.org/go.uber.org/zap/zapcore#Entry) before passing it through to the original core.

**Comment by danielbprice** [comment]
I have no real stake in the name-- except to say that, for discoverability-- I had assumed there would be such an option after discovering `DisableCaller` in the Config struct ( https://github.com/uber-go/zap/blob/master/config.go )
