### ISSUE TITLE
[Question Need Help] Question about Writer Lock

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#708]
Hey guys, I have a question about the `zapcore.WriteSyncer`

As for `internal/poll/fd_unix.go`

```go
// Write implements io.Writer.
func (fd *FD) Write(p []byte) (int, error) {
    if err := fd.writeLock(); err != nil {
        return 0, err
    }
    defer fd.writeUnlock()
    if err := fd.pd.prepareWrite(fd.isFile); err != nil {
        return 0, err
    }
```
here called `fd.writeLock()`.

I found the reference here
https://golang.org/src/internal/poll/fd_mutex.go
```go
// fdMutex is a specialized synchronization primitive that manages
// lifetime of an fd and serializes access to Read, Write and Close
// methods on FD.
type fdMutex struct {
	state uint64
	rsema uint32
	wsema uint32
}
```

seems the writer will be serialized by go.

But we still got a `write_syncer` here. Why?

https://github.com/uber-go/zap/blob/master/zapcore/write_syncer.go#L64
```go
func (s *lockedWriteSyncer) Write(bs []byte) (int, error) {
	s.Lock()
	n, err := s.ws.Write(bs)
	s.Unlock()
	return n, err
}
```

**Comment by arthurkiller** [comment]
ps. go 1.12

**Comment by arthurkiller** [comment]
@prashantv @NWilson @akshayjshah

**Comment by prashantv** [comment]
When opening files using [`zap.Open`](https://godoc.org/go.uber.org/zap#Open) (used internally when parsing configurations), we use [`zap.CombineWriteSyncers`](https://godoc.org/go.uber.org/zap#CombineWriteSyncers) which ensures no parallel `Write` calls. This is so when writing to multiple files, you don't get ordering issues, e.g., let's say you had 2 parallel writes W1 and W2. If these were written to multiple files (F1 and F2), it's possible for the following interleaving if W1 and W2 happen close to each other:

W1 writes to F1
W2 writes to F1
W2 writes to F2
W1 writes to F2

This would be a little confusing as looking at F1, you'd see W1 followed by W2. However, looking at F2, you'd see W2 followed by W1.

By locking around writes to possibly multiply files, it ensures that writes are seen in the same order for al files.

The lock is unnecessary for the case of a single file, but this case wasn't special-cased.

**Comment by arthurkiller** [comment]
@prashantv Thx for your reply.

So may I say `file.Write` is parallel safe in go?  `zap.Syncer` want to sync the `file.Write` between multi files just like what `tee` dose?

**Comment by NWilson** [comment]
@prashantv That makes sense, thanks very much for the explanation! Is there a code comment to explain that? I had read the zap code too and been puzzled - apologies if there is a comment and I just didn't see it.

**Comment by prashantv** [comment]
@arthurkiller So may I say file.Write is parallel safe in go? zap.Syncer want to sync the file.Write between multi files just like what tee dose?

I wouldn't say "safe" -- it may not cause a race, but it may still lead to interleaved writes. There's no guarantee that concurrent writes will be written fully, so if you are have 2 large parallel writes, let's say "1111" and "2222", there's no guarantee that the write will happen atomically, so instead of "11112222" or "22221111" you could get "11221122" or some interleaving.

Unless the documentation says explicitly that a type is safe for concurrent use, it's unsafe, and the [documentation for `os.File`](https://golang.org/pkg/os/#File.Write) does not explicitly say it will provide atomic writes.

@NWilson: There's no documentation about why we do the lock, but it's an implication of the above -- there's no guarantee that a writer is safe for concurrent use, but zap provides a logger that is [safe for concurrent use](https://godoc.org/go.uber.org/zap#Logger). To achieve this, it has to serialize access to the underlying writer. The [documentation for `Open`](https://godoc.org/go.uber.org/zap#Open) does mention that it locks them.

Closing out this task, as I don't think there's any changes required in zap.

**Comment by NWilson** [comment]
> zap provides a logger that is safe for concurrent use. To achieve this, it has to serialize access to the underlying writer.

I don't think that's true though - serialising access to the underlying writer is not necessary if the writer is already safe for concurrent use. For example, if the underlying writer is already locked (eg `*os.File`), then zap doesn't _need_ to add another layer of locking. When the Logger writes to underlying WriteSyncer, it first forms a buffer where the complete log entry is built, then passes that to the WriteSyncer in a single (atomic) Write call.

It's true that when writing to _multiple_ backends, you need to lock the combined MultiWriteSyncer object to ensure that the ordering is consistent between the backends. That's definitely worth a code comment, since it's not obvious (to me).

However, there are some remaining small things that don't seem right:
* `zap.New` does `errorOutput: zapcore.Lock(os.Stderr),`, which adds a lock that synchronises nothing at all (since os.Stderr is already locked). In this case, the lock isn't coordinating anything.
* The `zapcore.Lock` documentation has the following: `In particular, *os.Files must be locked before use.` That seems misleading; rather locking is needed for any Writer which isn't thread-safe (but `*os.File` is thread-safe so doesn't need additional logging).

I agree that `os.File` should document that it's safe for calls from multiple Goroutines. I've opened a PR to request that change upstream - we'll see what they say.

**Comment by prashantv** [comment]
> I don't think that's true though - serialising access to the underlying writer is not necessary if the writer is already safe for concurrent use.

Agree that there's no need to serialize access to the underlying writer if it can handle concurrent use. However, it's possible to [register custom schemes](https://godoc.org/go.uber.org/zap#RegisterSink) and there's no requirement that the opened sink is safe for concurrent access (as it's supposed to match the `io.Writer` interface, which similarly has no such guarantee). So it's not always clear what the underlying writer is, and what the capabilities are.

> I agree that os.File should document that it's safe for calls from multiple Goroutines. I've opened a PR to request that change upstream - we'll see what they say.

Can you link to the issue here so we can follow along. If the `*os.File` documentation states that it's safe to use from multiple goroutines, and it guarantees atomic writes (no interleaving of data), then we definitely should update our documentation, and can figure out whether we should special-case writing to a single `*os.File` to avoid locking.

**Comment by NWilson** [comment]
Thanks! https://go-review.googlesource.com/c/go/+/174957

**Comment by arthurkiller** [comment]
thx a lot

**Comment by arthurkiller** [comment]
@NWilson So let's focus on the beginning question, may I say `os.File` is paralle safe (atomic)? 😆

> https://golang.org/src/internal/poll/fd_mutex.go

```golang
// fdMutex is a specialized synchronization primitive that manages
// lifetime of an fd and serializes access to Read, Write and Close
// methods on FD.
type fdMutex struct {
	state uint64
	rsema uint32
	wsema uint32
}
```

I agree that `os.Writer` is an interface which did not ensure parallel safe. But `os.File` provide parallel safe has no conflict with this guarantee. Is that right? 

Thank you.

**Comment by arthurkiller** [comment]
> This is not correct when writing more than PIPE_BUF (typically 4096) bytes to a pipe.  The kernel can and will interleave bytes from simultaneous large write calls.

I get it. Thx a lot.

**Comment by xin-tsla** [comment]
Wondering the lockedWriteSyncer is for keeping consistency among multiple log files? If there is only one log file, does it log without locking work?
