### ISSUE TITLE
why global logger L() S() output nothing by default ?

### ISSUE THREAD

**Issue by dfang** [uber-go/zap#717]
is there anything like `log.Info` that can run anywhere without `NewDevelopment` or `NewExample` ?

eg. zap.Info, zap.Debug

and also, as https://blog.sandipb.net/2018/05/04/using-zap-working-with-global-loggers/

why  `zap.S().Infow("An info message", "iteration", 1)` outputs nothing 

related issues:
https://github.com/uber-go/zap/issues/127

**Comment by abhinav** [comment]
No, there is no function like `log.Info` that can be run without building a
logger first.

Zap prefers not to provide implicit default global behavior, favoring explicit
configuration in your `main()`.

The default global logger used by `zap.L()` and `zap.S()` is a [no-op logger][1]. 
To configure the global loggers, you must use [ReplaceGlobals][2].

  [1]: https://godoc.org/go.uber.org/zap#NewNop
  [2]: https://godoc.org/go.uber.org/zap#example-ReplaceGlobals

The approach we recommend is to not rely on global loggers at all. Instead,
build a logger in your `main()` and pass it down to the components that need
to perform logging operations explicitly.

Closing because the question was answered. Feel free to re-open.

**Comment by dfang** [comment]
hi,  why you guys don't like global loggers, is it for performance ?

btw, how to pass it down ?


 i got this error when `go run main.go`,  
```
../../go/pkg/mod/github.com/uber-go/zap@v1.10.0/stacktrace.go:28:2: use of internal package go.uber.org/zap/internal/bufferpool not allowed
```
config/logger.go
```
package logger

import (
	"github.com/uber-go/zap"
)

var Logger
func init() {
	Logger, _ := zap.NewDevelopment()
	// Logger, _ := zap.S()
	zap.ReplaceGlobals(Logger)
}
```

then in config/db.go

```
import github.com/x/y/config/logger

logger.Logger.Debugw("msg", "a", "b")
```

**Comment by abhinav** [comment]
Hello. No, we believe that it's cleaner software design to not rely on any
global state in our applications. We believe that the verbosity trade-off is
worth it. The trade-off of Zap may not be worth it for simple systems.

By "pass it down" I meant to instantiate the logger in your `main()`, not in
`init()`, and then passing it explicitly as an argument to all components that
need it, without ever using `zap.ReplaceGlobals`.

    func main() {
        ...
        
        logger, err := zap.NewDevelopment()
        if err != nil {
            ...
        }
        
        db := NewDatabase(..., logger)
        ...
    }

Again, this makes your code a little more explicit and verbose; this trade-off
may not be worth it for simple applications.

Finally, as mentioned in the other issue, your code fails to compile because
you're using the import "github.com/uber-go/zap". You need to change it to
"go.uber.org/zap".

**Comment by dfang** [comment]
mistook the repo name for the package name ...

thanks ！

**Comment by dfang** [comment]
due to my [code structure](https://github.com/qor/qor-example/blob/master/config/db/db.go#L26),   it's a little tricky for to use "pass it down" pattern.

is it possible to use "import then log" pattern ?

i mean configing  logger in a package, import it at where to log ....

**Comment by abhinav** [comment]
@dfang, you're free to use that pattern if it works for you.

**Comment by dfang** [comment]
@abhinav actually i failed to make it work.

config/logger.go
```
package logger

import (
	"go.uber.org/zap"
)

var Logger *zap.Logger

func init() {
	Logger, _ := zap.NewDevelopment()
	zap.ReplaceGlobals(Logger)
}
```

config/db.go
```
import  ..../logger

logger.Logger.Info ....
```

i got this error when `go run main.go`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17cc1c3]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x0, 0x1add784, 0x9, 0xc000230300)
	/Users/mj/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:264 +0x93
go.uber.org/zap.(*Logger).Info(0x0, 0x1add784, 0x9, 0xc000230300, 0x2, 0x2)
	/Users/mj/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:186 +0x44
github.com/dfang/qor-demo/config/db.init.0()
	/Users/mj/src/qor-demo/config/db/db.go:35 +0x2f0
exit status 2
```

**Comment by chrisxue815** [comment]
@dfang `Logger, _ := zap.NewDevelopment()` creates a new local variable named `Logger`, while leaving the package-level `var Logger *zap.Logger` uninitialized. Removing the colon `:` will probably fix the `invalid memory address or nil pointer dereference` error.

**Comment by xiaoxfan** [comment]
@dfang 
```
package logger

import (
	"go.uber.org/zap"
)

var Logger *zap.Logger

func init() {
	// Logger, _ := zap.NewDevelopment()  [you can't use := ]
        Logger, _ = zap.NewDevelopment()
	zap.ReplaceGlobals(Logger)
}
```

**Comment by shibumi** [comment]
Hi,

can we make this more clear in the documentation? I spent 10-30min wondering why the global logger produces no output.
Also, I am wondering why this works:

```go
package main

import "go.uber.org/zap"

func main() {
	logger, err := zap.NewDevelopment()
	if err != nil {
		panic(err)
	}
	zap.ReplaceGlobals(logger)
	foo()
}

func foo() {
	zap.L().Info("test")
}
```

I am playing around with this global logger right now, my program runs as expected, but I see concurrent panics from Go:

```
2021-12-06T00:31:40.433+0100    WARN    cli/create.go:53        set secretname to 
github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli.Create.func1
        /home/chris/go/src/github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/cli/create.go:53
github.com/spf13/cobra.(*Command).execute
        /home/chris/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /home/chris/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/chris/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        /home/chris/go/src/github.com/shibumi/kubectl-htpasswd/cmd/kubectl-htpasswd/main.go:16
runtime.main
        /usr/lib/go/src/runtime/proc.go:255
```

Any idea? Is it because I initialize the global logger in main, but use the global logger in a package called Cli? :D

**Comment by author-spirit** [comment]
New to zap, spent 2-3 hours in making zap logger global to files.
Really documentation is not clear without proper examples or flow.
Few minutes back I regretted using zap.
Thanks to this thread, now able to make it work across my app.
