### ISSUE TITLE
use Sugar oom , memory leak  

### ISSUE THREAD

**Issue by Anteoy** [uber-go/zap#719]
go version : 1.10 
zap version: Probably a code two or two years ago, it should be an old version.
how use: 
```
zap.New(zapcore.NewCore(
			zapcore.NewJSONEncoder(cfg),
			ws,
			config.Loglevel.toZapcoreLevel(),
		)).Sugar()
```
When my application's tcp connection went from hundreds of thousands to one million, my memory was slowed down.
I finally found the zap log is the problem by go pprof.
Then I delete these code about zap and my application worked fine.
By your Readme,
```
When performance and type safety are critical, use the Logger. It's even faster than the SugaredLogger and allocates far less, but it only supports structured logging.
```
Does this mean that sugur is not type safe?
and it cost a lots of memory?

**Comment by prashantv** [comment]
Unfortunately there is no information here the suggests a memory leak. It is possible performance was affected because you have too many logs.

Regarding specific questions:

> Does this mean that sugur is not type safe?

Sugar logger can be misused in a way the compiler cannot detect. E.g., if you do `sugarLogger.Warnw("my log message", "field 1")`, then the compiler cannot detect that field 1 is missing a value.

> and it cost a lots of memory?
Sugar logger is slower than the normal logger.
