### ISSUE TITLE
inconsistent display of zap.Time field with zero time struct

### ISSUE THREAD

**Issue by gwik** [uber-go/zap#737]
When logging a zero initialized time.Time struct the output is not consistent:

```go
zap.L().With("time", time.Time{}).Debug("zero time")
```
Will output the time: `1754-08-30T22:43:41.128654848Z` because calling `UnixNano()` then `Unix(0, nsec)` is not symetric in this case.
The correct output would be `0001-01-01 00:00:00 +0000 UTC` (with the same layout as above).

see https://gist.github.com/patdowney/b64a4fee790ac66dd1a2 that exhibit the issue.

Looking at zap.Time I was wondering why you don't pass the Time struct in the Interface field instead of converting to an integer. Maybe this is to avoid making a new reference to traverse for the GC ?

https://github.com/uber-go/zap/blob/425214515ff452748375576b20c82524849177c6/field.go#L180-L184

https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/zapcore/field.go#L141-L147

**Comment by prashantv** [comment]
Storing a `time.Time` directly in the `Interface` field would require an additional allocation, while storing the integer + the `*time.Location` avoids the allocation (since `*time.Location` is already a pointer).

Since zap is focused on performance, we made the choice to avoid allocations here.

I think we have a couple of options to fix this though:
 - If we care specifically about the zero case, we can create a new field type specifically for zero time, or store a special string value.
 - We can create a new field type that stores `time.Time` if the value is outside of the range of what `UnixNano` supports,
https://golang.org/pkg/time/#Time.UnixNano

**Comment by gwik** [comment]
Of course, storing in `interface{}` would make it escape to the heap.

> If we care specifically about the zero case, we can create a new field type specifically for zero time, or store a special string value.

I think storing a special string makes sense. I'm not sure this requires a new field type as the added cost would be very low if you're in the int64 range.

**Comment by prashantv** [comment]
After thinking about this more, I think it might actually be cleaner to just have 2 types of time fields:
 * The current type which uses `UnixNano()` and stores the int64 field
 *A new type which uses an `interface{}` and stores the `*time.Time`.

The latter type should only be used if the field cannot be stored as an `int64`.
