### ISSUE TITLE
Taking advantage of Time.AppendFormat

### ISSUE THREAD

**Issue by vrischmann** [uber-go/zap#783]
Hi,

I'm opening this issue to discuss a potential API change to the [buffer type](https://github.com/uber-go/zap/blob/master/buffer/buffer.go).

I have a custom encoder where times are encoded as strings formatted with the `Format` method from Go. Currently I have to do this:

```
enc.buf.AppendString(value.UTC().Format(time.RFC3339))
```

but it would be nice if we could just use the [AppendFormat](https://golang.org/pkg/time/#Time.AppendFormat) method to avoid an allocation.

I'm thinking of adding a method to the buffer type with this signature: `AppendTime(t time.Time, layout string)`.

Another solution would be to allow users to set the byte slice used by the buffer type so that I could write this:

```
buf := enc.buf.Bytes()
buf = value.AppendFormat(buf, time.RFC3339)
enc.buf.SetBytes(buf)
```

less elegant than having `AppendTime` but maybe a good solution if you don't want to special case times in the buffer type.

**Comment by prashantv** [comment]
I'm not opposed to adding the `AppendFormat` function to the buffer type. It currently only deals with types that are part of the language, but I don't think supporting common standard library types is a bad idea.

That said, if we do support `AppendFormat` in the buffer type, it should be used within zap itself by the default encoder. This may be tricky since the [`TimeEncoder`](https://godoc.org/go.uber.org/zap/zapcore#TimeEncoder) type receives a [`PrimitiveArrayEncoder`](https://godoc.org/go.uber.org/zap/zapcore#PrimitiveArrayEncoder) which doesn't (intentionally) support append time.

Since we can't extend the interface in 1.0, the included time encoders in zap could try and cast the passed in encoder to see if it supports an `AppendFormat` function, and if so, use it. I'm not sure what the performance impact of the cast would be, so we should measure that.

**Comment by vrischmann** [comment]
Just want to say thanks for working on this, much appreciated.
