### ISSUE TITLE
creating new Logger/Encoder implementations outside of the zap package isn't possible?

### ISSUE THREAD

**Issue by campbellr** [uber-go/zap#79]
While attempting to write a simple stub `Logger` implementation for some tests, I noticed that it doesn't currently seem possible to do outside of the `zap` package (assuming you don't want to ignore the log fields).

The main problem is that there doesn't appear to be a way for an encoder to get the any information from a `Field` (both `addFields` and `Field.addTo` are unexported)

Am I missing something? I'll admit that I'm not familiar with the codebase.

**Comment by akshayjshah** [comment]
You're definitely not missing anything - we'll need to expose more API surface before 1.0 so that this is easy. We're currently working on #57, which will force us to find a clean way to do this.

That said, there's already a test stub available in the [spy](https://godoc.org/github.com/uber-go/zap/spy#New) sub-package. Keep in mind that all the zap APIs are pre-1.0 and will probably change a bit!

**Comment by akshayjshah** [comment]
Closing this as a near-duplicate. @campbellr - if you're interested, please follow #57.
