### ISSUE TITLE
Capturing log for unit tests

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#794]
To capture logs of a custom logger for unit tests, what do you suggest? I see in logger_test.go there is a TestLogSpy which is implemented to do that but that is not gonna work for a custom logger which writes in stdout.

**Comment by prashantv** [comment]
The [`observer`](https://godoc.org/go.uber.org/zap/zaptest/observer) package captures log output, and lets you filter and get the logs.

**Comment by adibrastegarnia** [comment]
@prashantv 
That's great. I will give it a try.

**Comment by adibrastegarnia** [comment]
@prashantv 
The examples that I saw are based on this fact to create a logger based on the new core of observer. I don't want to touch my logger because the point is to test the custom logger and see if it is configured properly or not. Can you provide me a to the point example of this scenario if it is possible?

**Comment by abhinav** [comment]
@adibrastegarnia We may be misunderstanding your question, but you
cannot capture the output of a logger configured for production in
tests without changing the configuration of that logger.

If you can't change the Core because you have a custom Core, that means
you're trying to validate the actual text output of the logger. In that
case you need to customize your Core to write to a `WriteSyncer` which
makes the contents available to you. A `*bytes.Buffer` wrapped with
zapcore.AddSync and zapcore.Lock would suffice for that.

**Comment by adibrastegarnia** [comment]
@abhinav 
Thanks for the explanation. That makes sense.
