### ISSUE TITLE
In init() can not configure log to stdout.

### ISSUE THREAD

**Issue by mikezhang0** [uber-go/zap#805]
```golang
package zap

import (
	"go.uber.org/zap"
)

var testlog *zap.Logger

func init() {
	cfg := zap.NewProductionConfig()
	cfg.OutputPaths = []string{"stdout"}
	testlog, _ = cfg.Build()
}

func Example() {
	testlog.Sugar().Infof("a %v", 1)
	// Output: {"level":"info","ts":1585243999.8738391,"caller":"zap/zap_test.go:31","msg":"a 1"}
}

```

**Comment by prashantv** [comment]
Zap is working as intended, it's outputting to stdout:
https://play.golang.org/p/Ki_fTJPaByO

I think your issue is that when running tests, the test runner replaces `os.Stdout`, and compares output using that replaced `os.Stdout`, but the zap logger was created before `os.Stdout` was replaced.

If you want to verify logs, consider using the zaptest/observer package: http://go.uber.org/zap/zaptest/observer
