### ISSUE TITLE
RedirectStdLog isn't formatting as expected or outputting to log file

### ISSUE THREAD

**Issue by troypoulter** [uber-go/zap#817]
You can test out the issue I'm describing here: https://play.golang.org/p/fOvGNaDf-wL

I've configured a `zap` logger to:
- Use the `ISO8601TimeEncoder` which outputs it to something like this: `2009-11-10T23:00:00.000Z`
- Output to a file called `test.log`
- Redirect the standard log to my logger

What I'd expect to happen is when I redirect the standard logger to use the `zap` logger I've configured, it will format it in the same manner and output to the log file.

This doesn't appear to be happening and the Go Playground link I provided at the top reproduces this behavior.

I've been reading through the docs all day trying to work it out and thought it'd be best to ask here.

Please let me know if you need any additional details.

**Comment by prashantv** [comment]
The issue is the use of `defer undo()`. The `undo` function reverts the change made to redirect the standard logger, and you're calling `defer undo()` in `InitLogger`, so it'll run before `InitLogger` returns -- and hence before you call your log statements.

Deleting the `undo` call seems to fix the issue and it works as expected.

**Comment by troypoulter** [comment]
Ahh fantastic! Thank you @prashantv!

Here is a playground link for reference in case other people come across this: https://play.golang.org/p/k22KWuqewJ7

I was using the code from the example in the docs and didn't think about what the `defer undo()` is really doing - https://pkg.go.dev/go.uber.org/zap?tab=doc#example-RedirectStdLog.
