### ISSUE TITLE
Performance testing of the zerolog library

### ISSUE THREAD

**Issue by YIDWang** [uber-go/zap#821]
Zerolog's readme performance tests are better than zap's but zap's readme says the performance tests are due to zerolog。

Can you answer that?
![image](https://user-images.githubusercontent.com/20499178/80270996-80892a00-86ef-11ea-92f4-6e56a1aba76f.png)

**Comment by YIDWang** [comment]
https://github.com/rs/zerolog

**Comment by prashantv** [comment]
The benchmarking code in zap is included, so you can compare it yourself:
https://github.com/uber-go/zap/tree/master/benchmarks

I think the difference is likely because of zap using non-sampled logs (we're comparing the cost of logging everything), while zerolog's benchmarks may be sampled based on #659
