### ISSUE TITLE
`zaptest.Observer` does not capture the initial `Field`s

### ISSUE THREAD

**Issue by CAFxX** [uber-go/zap#859]
`zaptest.Observer` does not capture fields set using `InitialFields`, but it captures fields set with each event. Arguably, this is an undesirable and unintuitive behavior.

```go
// in normal code: setup the logger
config := zap.NewProductionConfig()
config.Level = zap.NewAtomicLevelAt(level)
config.DisableStacktrace = true
config.Sampling = nil
config.OutputPaths = []string{"stdout"}
config.ErrorOutputPaths = []string{"stderr"}
config.InitialFields = map[string]interface{}{"tag": "value"}
logger := config.Build()

// in testing code to capture the log events emitted by other parts of the code
o, logs := observer.New(level)
logger = logger.WithOptions(
	zap.WrapCore(func(zapcore.Core) zapcore.Core {
		// there is no way here to wrap the original core so that initial fields are preserved
		return o
	}),
)

l.Info("This is an INFO message", zap.String("hello", "world"))

all := logs.AllUntimed() # all is dumped in the outputs below
```

# Expected result

I expect the initial fields to be included in the events.

```
[{{info 0001-01-01 00:00:00 +0000 UTC  This is an INFO message /some/path.go:47 } [{tag 15 0 value <nil>} {hello 15 0 world <nil>}]}]
```

# Actual result

The initial fields are missing.

```
[{{info 0001-01-01 00:00:00 +0000 UTC  This is an INFO message /some/path.go:47 } [{hello 15 0 world <nil>}]}]
```

**Comment by prashantv** [comment]
This is expected because of how zap works:
 * Cores encode fields as they are added
 * `WrapCore` cannot go back, as the previous fields are not stored unencoded

Similarly, doing `logger = logger.With(zap.String(....))` followed by a `WrapCore` will not encode the previously added fields.

This is a core design of zap, which is focused on performance, and it's likely that the current `WrapCore` is expected by other users, so we cannot change this behaviour.
