### ISSUE TITLE
set log level for global zap logger 

### ISSUE THREAD

**Issue by celesteking** [uber-go/zap#870]
I'm trying to set a log level for 3rd party lib that's using this package. 

Go search in Google "zap logger set level" and you'll see the number of people that are struggling to do that. Why should it be so complicated? Couldn't you just come up with a simple and proper method to do that?

The app is doing this in init(): `logger = zap.L().Named("dat:sqlx")` 

Is there a way to override that global level?

Thanks.

**Comment by prashantv** [comment]
You'll need to create a new logger with the appropriate level, and use [`ReplaceGlobals`](https://godoc.org/go.uber.org/zap#ReplaceGlobals).

https://godoc.org/go.uber.org/zap#L
> L returns the global Logger, which can be reconfigured with ReplaceGlobals. It's safe for concurrent use.

zap doesn't have a `SetLogger` method, because a child logger passed to some library should not have the ability to change the log level for all other loggers. The design separates the level  from the logger, hence why there is no `SetLevel` function, and we don't expect to add one.

**Comment by celesteking** [comment]
This should really be documented in sane human manner. Just generating an APIdoc is the worst possible scenario after not having documentation at all.
Try searching on google, you'll see how many people are struggling.

**Comment by abhinav** [comment]
@celesteking Please use a more respectful tone if you want your feedback to be heard.
Consider going over https://golang.org/conduct#values engaging again.
Locking this thread for now.
