### ISSUE TITLE
Does zap support formatted output of JSON to a file, as shown in the following figure:

### ISSUE THREAD

**Issue by Huangsh17** [uber-go/zap#895]
Does zap support formatted output of JSON to a file, as shown in the following figure:
![image](https://user-images.githubusercontent.com/27496367/102576387-5aa60f00-4130-11eb-9368-97a4e013aa86.png)

**Comment by Tak1za** [comment]
I don't think it comes out of the box.
[https://github.com/uber-go/zap/issues/530](url)

**Comment by abhinav** [comment]
@Huangsh17 can you clarify what form you want the output in?
The contents of that screenshot are not valid JSON.

If you just want pretty-printed JSON, Zap does not support that. Depending on
your needs, you may pipe the output of Zap to `jq`, or write a wrapper around
the Zap JSON encoder to achieve that.

**Comment by Huangsh17** [comment]
> @ Huangsh17您能否阐明输出的格式？
> 该屏幕截图的内容不是有效的JSON。
> 
> 如果您只想要漂亮的JSON，Zap不支持。根据
> 您的需求，您可以将Zap的输出传递给`jq`，或围绕
> Zap JSON编码器编写包装器以实现此目的。

It is similar to formatting and outputting JSON on the web page, which looks more beautiful and clear, rather than outputting JSON line by line in the file

**Comment by abhinav** [comment]
I understand. Zap doesn't come with a pretty encoding out of the box largely
because its output is meant to be consumed by machines: systems like Logstash,
for example.

We don't have any immediate plans to add a pretty encoder because styling of
the output is preference-based, and one can be implemented as an external
component while keeping the core of Zap slim.

You can write a custom Zap encoder by implementing [zapcore.Encoder][1] to
meet your specific needs. There are also community-authored encoders that
provide prettier output that you may find useful.

[1]: https://pkg.go.dev/go.uber.org/zap/zapcore#Encoder

All that said, if there's a good standard for readable structured log output
in a console, we would be open to the idea of shipping it with Zap.

**Comment by Huangsh17** [comment]
> 我明白。Zap没有开箱即用的漂亮编码，这在很大程度上是
> 因为Zap的输出供机器使用：例如Logstash之类的系统
> 。
> 
> 我们尚无立即计划添加漂亮的编码器的计划，因为
> 输出的样式基于首选项，并且可以将其实现为外部
> 组件，同时保持Zap的核心苗条。
> 
> 您可以通过实现[zapcore.Encoder](https://pkg.go.dev/go.uber.org/zap/zapcore#Encoder)来编写自定义的Zap编码器，以
> 满足您的特定需求。也有社区授权的编码器，可
> 提供更有用的输出。
> 
> 综上所述，如果
> 在控制台中有一个可读结构日志输出的良好标准，我们将对使用Zap交付它的想法持开放态度。

okay, thank you

**Comment by abhinav** [comment]
Closing since the question was answered.
