### ISSUE TITLE
Allow the key/value parameters of Infow and relatives be configurable.

### ISSUE THREAD

**Issue by lucasoares** [uber-go/zap#905]
Currently all key/value provided to a Infow is encoded as this example:

```go
zap.S().Infow("Test with labels", "label", "test", "label2", "test2")
```

Will result in this output:
```json
{
  "level": "info",
  "ts": 1610470638.8462012,
  "caller": "deckard/main.go:38",
  "msg": "Test with labels",
  "label": "test",
  "label2": "test2"
}
```

I need to index application logs to a third party and those labels must be indexed differently so we can perform better searching and dashboards on them. Currenly my logs (Java applications) have labels that are encoded in a way that we know what is a label. Just like this:
```json
{
  "severity": "DEBUG",
  "timestamp": {
    "seconds": 1610469308,
    "nanos": 360000000
  },
  "message": "Test",
  "labels": {
    "label": "test",
    "label2": "test2"
  }
}
```

Looking the docs and examples I think this is not supported right know, right?

Thanks.

**Comment by abhinav** [comment]
Hey, [`zapcore.EncoderConfig`][1] provides basic control over the default
field names like caller, level, time, etc. as well as how they're encoded. For
example:

[1]: https://pkg.go.dev/go.uber.org/zap@v1.16.0/zapcore#EncoderConfig

```
zapcore.EncoderConfig{
  MessageKey: "message",
  LevelKey: "severity",
  TimeKey: "timestamp",
  EncodeLevel: func(lvl zapcore.Level, enc zapcore.PrimitiveArrayEncoder) {
    enc.AppendString(lvl.CapitalString())
  },
  // ...
}
```

This will get you as far as,

```
{
  "severity": "INFO",
  "timestamp": 1610470638.8462012,
  "caller": "deckard/main.go:38",
  "message": "Test with labels"
  "label": "test",
  "label2": "test2"
}
```

Unfortunately, the `EncodeTime` customization only allows primitive
representations of time, and does not support complex objects (`{"seconds": .., "nanos": ...}`).

However, with the pieces above, you should be able to wrap Zap's JSON encoder
with a custom encoder and override the [`AddTime`][2] method to get the
desired behavior.

[2]: https://pkg.go.dev/go.uber.org/zap@v1.16.0/zapcore#ObjectEncoder.AddTime

---

As for combining the labels, you need to supply them to Zap explicitly as a
single object:

```
zap.S().Infow("test with labels", "labels", map[string]string{
  "label": "test",
  "label2", "test2",
})
```

If performance is a concern here, you may want to build a custom `Labels` type
and implement [`zapcore.ObjectMarshaler`][3] on it.

```
type Levels map[string]string

func (lvls Levels) MarshalLogObject(enc ObjectEncoder) {
  for k, v := range lvls {
    enc.AddString(k, v)
  }
}
```

And then,

```
zap.S().Infow("test with labels", "labels", Levels{
  "label": "test",
  "label2", "test2",
})
```

[3]: https://pkg.go.dev/go.uber.org/zap@v1.16.0/zapcore#ObjectMarshaler

That said, if you wrap the Zap's JSON encoder with a custom encoder, you can
collate fields you want by overriding [`EncodeEntry`][4]. Inside your
implementation, filter out the provided fields based on your chosen criteria
(like `strings.HasPrefix(field.Key, "level")`), build a `map[string]string`
out of them, and add a new field for them.

[4]: https://pkg.go.dev/go.uber.org/zap@v1.16.0/zapcore#Encoder.EncodeEntry

Hope this helped. Closing because the question was answered. Feel free to
reopen or open a new issue.

**Comment by lucasoares** [comment]
Hello @abhinav thank you for the complete answer.

Do you have any example to wrap Zap's JSON encoder?
I'm new to Golang and also to Zap so this example would be helpful.

Thanks!

**Comment by lucasoares** [comment]
Hello again @abhinav 

The thing about labels is that I have labels inside the context and I want all of them to be logged together.

With your suggestion all labels will be replaced every time I log something.

I also can't re-open the issue but I will wait for reply here before opening a new one. Thanks.
