### ISSUE TITLE
1.17 release

### ISSUE THREAD

**Issue by ptabor** [uber-go/zap#942]
On behalf of https://github.com/etcd-io/etcd wanted to check perspectives for zap-1.17 release. 

etcd is currently depending on: `go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19`. 

The unstable dependency was taken due to 89e382035d3a984a01e6c9c8be5462f11efac844 (grpclog.LoggerV2). 
Now we are preparing etcd release 3.5.0 that is needed to unblock kubernetes 1.22. 

The etcd release is tracked by: https://github.com/etcd-io/etcd/issues/12970

**Comment by abhinav** [comment]
Hey there! We're not opposed to tagging a new release but we might have to back out #897 if we do that right now.

We have someone working on a version of #782 to address some of the outstanding issues. Until that's ready, though, we can't tag a release that includes the new Clock interface (added in #897) because we expect the work in #782 to affect that interface.

CC @prashantv

**Comment by ptabor** [comment]
Thank you for the response. I think we are talking about ~2 weeks timeline for promoting 3.5.0-beta to 3.5.0 at which state we should have stable dependencies.

**Comment by hexfusion** [comment]
Hi @abhinav @ptabor following up on this any chance for a release this week?

**Comment by abhinav** [comment]
Hey @hexfusion. @prashantv and I decided last week that if we could get our reworked version of #782 in by today, we'd ship that. Otherwise, we'll back out #897 for this release (because it's getting changed in #948).

We'll try to tag the release today.
